---
editor: source
---

# ВВЕДЕНИЕ {.unnumbered}

Данный отчет посвящен построению формальных и функциональных моделей, лежащих в основе языковых компетенций, рассуждений и информационных взаимодействий когнитивных агентов, а также эмпирической верификации этих моделей. В фокусе внимания находятся (а) унификация формальных методов анализа когнитивного и языкового многообразия в логике, лингвистике и философии; (б) исследования малых языков с использованием полученных моделей. Эмпирическая верификация включает в себя исследование и документацию языков России и постсоветского пространства, включая диалекты, различные регистры и пограничные варианты русского языка в синхронной, диахронической и типологической перспективе. Это предполагает теоретическое и квантитативное моделирование языковых явлений и естественных рассуждений, а также создание цифровых инструментов и лингвистических ресурсов, в том числе образовательных.

В ходе реализации проекта были решены следующие задачи:

- разработаны формальные методы логического и лингвистического анализа факторов, влияющих на когнитивную обработку информации в условиях языкового многообразия;
- осуществлены сбор и анализ полевых материалов (элицитация, тексты и переводы текстов); созданы новые инструменты и ресурсы по языкам России и постсоветского пространства (корпуса, словари, базы данных по отдельным языковым явлениям, в том числе наборы данных, которые могут быть использованы для тестирования компьютерных моделей на способность осваивать различные грамматические категории естественного языка);
- созданы новые цифровые ресурсы и инструменты для изучения русского языка и культуры в различных перспективах (базы данных, корпуса, архивы, словарные платформы );
- осуществлена разработка комплексной цифровой среды для хранения и анализа разноплановых языковых данных на материале малых иранских языков;
- проведено квантитативное моделирование языковых систем на основе корпусов и словарей (в том числе произведенных в ходе реализации проекта), а также данных языковых экспериментов;
- реализованы фундаментальные исследования: моделирование языковых явлений на основе данных языков России (включая русский) и языков постсоветского пространства; апробация компьютерных моделей (включая современные методы искусственного интеллекта) на языковом материале;
- проведено синхронное изучение пограничных языковых явлений: интерференции, прагматики, дискурса, а также синтаксическое моделирование языковых единиц;
- осуществлено типологическое описание избранных зон русского языка: разработка и редактирование типологических анкет; описание фрагментов лексического профиля русского языка на типологическом фоне; выявление ключевых особенностей диахронических процессов в русской признаковой и глагольной лексике в широкой типологической перспективе и со специальным акцентом на близкородственных славянских, а также иранских языках;
- проведена разработка нейросетевых методов 1) для коррекции текстов, написанных носителями русского языка, в т. ч. на иностранных языках; 2) для морфологического и синтаксического анализа исторических текстов; осуществлено компьютерное моделирование дискурса, в частности академического;
- выполнено исследование закономерностей в области прагматических функций многословных последовательностей в различных регистрах академической речи, которые проявляются в академических текстах на английском языке, написанных носителями русского языка.

Во Введении комплексно описаны основные направления исследовательского проекта.

В @sec-typology освещаются типологические исследования в пределах трех ареалов: Кавказского, Памирского и Северной Евразии (включая Арктику). Для языков Кавказа исследуется ареальная и генетическая вариативность дискурсивных единиц. Малые иранские (языки Памира, главным образом шугнанский) изучаются типологически в отношении целого ряда категорий и свойств, которые позволяют моделировать соответствующие языковые системы для обеспечения их цифровыми ресурсами. Ареал Северной Евразии и Арктики типологически описывается в двух аспектах: морфосинтаксис пространственных отношений и фонетика-фонология-просодия. Отдельный подраздел составляют лексико-типологические исследования, развивающие оригинальную научную школу. Они опираются на широкий круг языков, не связанных друг с другом географически или генетически.

В @sec-language описаны результаты частных исследований в области русского языка и других языков России. Если в @sec-typology приводятся результаты типологических исследований, представляющих явления языков в ареальной и генетической сопоставительной перспективе, то частноязыковые исследования предполагают фокус на одном языке, в том числе нестандартных вариантах языка, связанных с особым характером языкового опыта. Анализ языкового материала осуществляется методами и инструментами корпусной и полевой лингвистики. 

В области исследования языков России и приграничных стран были особенно подробно изучены морфосинтаксис и семантика глагольных и именных форм, а также диалектная вариативность (тундровый ненецкий язык, лесной ненецкий язык, удмуртский язык, ительменский язык, шугнанский язык, эвенский язык, кильдинский саамский язык, эвенский язык, уильтинский язык, эрзянский язык) и особенности нестандартной речи в условиях языковой утраты. 

В области исследований русского языка рабочая группа корпусных технологий в 2025 году развивала корпуса нестандартной русской речи (инофонов, детей, студентов, осваивающих академический регистр как новую систему письма). Обследовались особенности русского языка, связанные с вариативностью выражения смыслов и динамикой речевой нормы. Результаты также представлены в @sec-language. В частности, была осмыслена метафоризация глаголов движения в русской речи русско-казахских билингвов, а также разработаны принципы разметки базы устойчивых реактивных формул в диалоге --- рутин; были классифицированы черты схождения в нестандартных орфографических решениях современных детей, начинающих писать по-русски, наивных пишущих, не получивших полноценного школьного образования (1919--1929 годов рождения), и авторов тех эпох, когда современный речевой стандарт не был еще кодифицирован (восемнадцатого и девятнадцатого столетий). Был предложен новый параметр, отличающий русские контрфактивные условные предложения от других типов гипотетических условных конструкций. Были проанализированы случаи употребления предложений с подчинительными союзами как самостоятельных, вне сложноподчиненного предложения. Развивался русский учебный корпус, аккумулирующий русскую речевую продукцию инофонов и эритажных говорящих.

В @sec-formal отражены результаты исследования языков России формальными методами. По мере накопления эмпирических знаний о языках России все более актуальным становится построение новых и уточнение существующих теоретических моделей с учетом этих знаний. Разрабатываемые рабочей группой проекта формальные модели служат более мощным и современным инструментом анализа эмпирических языковых данных, чем традиционные подходы. Одной из задач исследования является представление данных языков России с использованием формальных моделей (формальной семантики, синтаксиса, прагматики). Эта задача достаточно объемная и многоаспектная. В 2025 г. для моделирования были выбраны следующие классы явлений: кодирование временных отношений в языке, анафора и связывание, передвижение в полипредикации, согласование с нетривиальными контролерами, полярность (логические операторы в языке). Для решения этой задачи разрабатывались ресурсы, служащие эмпирической базой для разрабатываемых моделей. Исследования велись на материале русского, а также хантыйского, абазинского, кильдинского саамского, мишарского татарского и других языков России.

@sec-logic развивает формальный подход к описанию естественного языка и мышления --- в теоретическом аспекте. Исследование коммуникативных компетенций ограниченно рациональных агентов было направлено на поиск новых подходов к разрешению затруднений, которые препятствуют эффективному информационному обмену в условиях языкового и когнитивного многообразия. В центре внимания находились такие классические для логики и формальной эпистемологии проблемы, как концептуальная неопределенность и референциальная непрозрачность, скептицизм в отношении значения, логические и семантические парадоксы. Особое внимание уделялось новым теоретическим и практическим вызовам, обусловленным развитием неклассических логических систем, систем искусственного интеллекта и социальных сетей. Методологически исследование характеризовалось укорененностью в существующих логико-философских традициях. Обращение к их истокам осуществлялось не в их сугубо исторической, а в реактуализирующей эти традиции перспективе. Оно сопровождалось их переосмыслением в контексте современных проблем семантики, семиотики и когнитивных наук.

В @sec-computer отражены результаты, полученные рабочей группой по разработке учебных корпусов. Такие корпуса стали эффективным инструментом современных образовательных технологий, необходимых для сохранения языкового богатства в следующих поколениях. В частности,  создаются инструменты для отслеживания сходства учебных текстов, написанных инофонами, и текстов, написанных носителями. Классическим жанром для обучения языку является эссе на заданную тему, которое содержало бы элементы обоснования точки зрения обучающегося. Для автоматического сравнения эссе инофонов и носителей предложены оригинальные разработки. К ним относятся инструменты для автоматического обнаружения ошибок разных уровней: не только в грамматике, но и в синтаксисе, логической структуре предложения или порядке следования фраз при обосновании автором своей точки зрения. 

Для успешного решения этих задач необходимо поместить изучаемый язык в общий языковой контекст. В связи с этим были проведены исследования риторической структуры учебных текстов и осуществлено её сравнение со структурой текстов, написанных профессионалами, работающими на выбранном языке. Предложен метод сравнения структуры высказываний на разных языках, который позволит выявить влияние родного языка обучаемого на структуру порождаемого им текста и исправлять его непосредственно в процессе обучения.

Новой задачей является использование больших моделей в автоматизации образовательных технологий. В 2025 г. выделены различные характеристики синтетических, т.е. генерируемых автоматически, текстов, описаны возможности использования больших языковых моделей для решения ряда задач автоматической обработки больших данных на естественном языке, а также представлены собранные рабочей группой наборы данных, примененные для дообучения моделей в целях реализации прикладных проектов для государства и общества.

Деятельность рабочей группы учебных корпусов направлена на внедрение технологий и ресурсов, которые разрабатываются в рамках проекта для открытого использования как лингвистами, так и широким кругом потребителей. Результаты этой деятельности также представлены в @sec-computer.
