---
editor: source
---

# ЗАКЛЮЧЕНИЕ {.unnumbered}

Подводя итог данному разделу, отметим, что в рамках проведенных в 2025 году типологических исследований детально описаны императивные междометия в языках Кавказа; именные части речи, сложные глаголы, грамматический род и дейксис в иранских языках; морфосинтаксис пространственной сферы в северных языках. Целостное описание получили лексические группы «мешать» на материале большого числа языков и «менять» в русском языке в типологической перспективе. Получены существенные результаты для малых иранских (памирских) языков в отношении  таджикских заимствований в шугнанском, исконной лексики в объеме списка Сводеша для шугнанского и бартангского. Зафиксированы типологические особенности в сфере образования звуков, ударения и интонации в языках северного ареала, а также закономерности фонетической адаптации таджикских заимствований в шугнанском. Созданы и совершенствуются электронные ресурсы для машинного перевода на базе шугнанского и других памирских языков.

В целом сопоставительные исследования языков разных ареалов в типологической перспективе позволяют выявить общие и специфические черты родственных и неродственных идиомов, таким образом  расширяя представление современной науки о языке в сфере теории универсалий и идиоэтнического лингвистического своеобразия. Особый интерес представляют оригинальные методики лексико-типологического анализа, реализованные на материале двух семантических зон. Изучение разных языковых уровней и  аспектов (звукового строя и интонации, грамматики, лексики) позволяет выявить и интерпретировать  такие черты языковых систем и функционирования языков, которые в перспективе могут скорректировать знание об устройстве и вариативности человеческой коммуникации в целом, об особенностях соотношения языковых черт, проявляющихся в конкретном языке совместно или порознь. Создание цифровых ресурсов на материале отдельных языков (корпусов, баз, словарей) служит общей задаче накопления лингвистических данных для их последующего сопоставления и уточнения. Существенно, что такие ресурсы вносят вклад в сохранение малых языков и дают возможность сопоставлять их друг с другом и с крупными языками, а также формируют основу для диахронического анализа. В процессе  реализации проекта 2025 года существенно расширены представления о языках трех ареалов: Кавказа, Памира и севера, включая Арктику. Особенно ценны описания, построенные на материале уникальных эмпирических данных, собранных в ходе экспедиций.

Представьте, что здесь заключение для частноязыкового.

Таким образом, в результате исследований были получены уточнения формальных моделей (как в области формальной семантики, так и синтаксиса) для следующих областей: семантика и синтаксис видо-временных категорий, анафора и связывание, свойства логических операторов, дистантные передвижения в полипредикации. Для этого привлекались данные русского, хантыйского, абазинского, кильдинского саамского, мишарского татарского и др.
Для исследований русского языка активно применялись экспериментальные методы, которые позволяют верифицировать модели, часто основанные на интроспекции. Кроме того, экспериментальные методы позволили выявить новые нетривиальные особенности согласования в русском языке, ранее не учитываемые в теории. Материалы других языков были получены в ходе полевых исследований методом элицитации. Эти методы получили дальнейшее развитие, в частности, применялись современные методы семантического опроса.

Для развития эмпирической базы для дальнейших исследований был разработан ряд ресурсов, некоторые из которых открыты для общего доступа (в частности, корпус текстов на хантыйском языке, типологическая база нефинитных форм в языках северной Евразии).

В результате разработан эксплицитный формальный анализ семантики наречного сдвига в казымском хантыйском, позволяющий предсказать несовместимость относительного времени с индексикальными наречиями: относительное время связывается локально доступным временем матричной клаузы, а наречия интерпретируются относительно момента речи. Также разработана эксплицитная семантическая модель причастного показателя -(m)a в кильдинском саамском, объясняющая все употребления этого показателя (показателя упорядочивающего аспекта, вводящего отношение предшествования). Исследование синтаксических свойств дистантного скрэмблинга в мишарском татарском показало, что такой скрэмблинг возможен вне зависимости от падежного маркирования субъекта, что ставит под сомнение описательную и объяснительную адекватность ряда существующих моделей. Основными результатами исследования грамматических свойств логических операторов стало уточнение эмпирической картины — необходимый этап при верификации гипотез в основе эксплицитной формальной модели соответствующих явлений. Выявлены факты, ставящие под сомнение анализ русских местоимений на -либо как выражений отрицательной полярности, и выдвинута альтернативная гипотеза, подлежащая дальнейшей разработке. В результате экспериментальных исследований уточнены ограничения на лицензирование отрицательных и реципрокальных местоимений в русском языке, а также ограничения на согласование по роду и числу, в том числе в зависимости от референциального статуса контролёра согласования. Исследование синтаксического поведения анафорических элементов в казымском хантыйском позволило описать ограничения на употребления двух классов местоимений — демонстративов и прономиналов, заложив основу для разработки модели их поведения.
Исследования в рамках уточнения формальных моделей отдельных языковых явлений, а также более глубокое их рассмотрение с использованием экспериментальных методов велись в следующих направлениях: семантика и синтаксис грамматических глагольных категорий, анафора и связывание, исследование согласования экспериментальными методами, грамматические свойства логических операторов.

Исследование взаимовлияния логических и лингвистических факторов в процессах обработки информации рациональными агентами с ограниченными   логико-когнитивными ресурсами  позволило построить формальные модели для разрешения ряда затруднений логико-семиотического характера, возникающих  в условиях языкового и  мультиагентного многообразия.

В результате исследования была осуществлена реактуализация семиотического наследия Ч-С. Пирса. Методология синехизма, намеченная в его поздних трудах, применена к решению актуальных задач обоснования междисциплинарного трансфера в научных коммуникациях, включающих искусственный интеллект. Разработана семиотическая модель трансформации структурных элементов интернет-мемов, использующая концептуальный аппарат семиотики Ч.-С. Пирса (понятия иконичности, типа, знака и привычки вывода). В актуальной ситуации плюрализма логических систем предложена реконструкция классического аргумента Г. Фреге против “логических чужаков”, обуславливающего признание когнитивного многообразия рационально рассуждающих агентов  психологизмом в логике.     

Предложены различные модификации формальной семантики перформативов,  позволившие сформулировать аргументы за и против скептицизма относительно значения.  Разработаны новые подходы к разрешению парадоксов неопределенности, основанные на критике ее эпистемической интерпретации. С использованием аппарата эпистемической логики построены соответствующие формализации. 

Выявлены и экспериментально подтверждены различия в дистрибуции пропозициональных глаголов и степени коммитмента  в контекстах со слифтами и стандартными вложенными конструкциями. На основе дихотомии типов обновления дискурса (ассерций и импозиций) построена формальная модель этих различий.   Предложена формальная модель эвиденциальных конструкций, верифицированная  анализом морфем первого и второго прошедших времен коми-зырянского языка.

В данном разделе был рассмотрен язык учебных текстов и язык профессионалов, работающих на данном языке. В качестве профессионального языка было предложено использовать тексты различных научных работ и новостные тексты. Были разобраны не только логически корректные рассуждения, но и рассуждения, обладающие теми или иными недостатками в рассуждениях, например, фейковые новости или новости с неполными рассуждениями. В разделе показывается, что синтаксические связи между парами и тройками слов может служить для анализа сходства структуры предложений в разных языках.  Также предлагается новый инструмент, позволяющий обучающимся автоматизировать проверку своих работ и за счёт этого сократить время отклика от преподавателя. 

Таким образом, получены данные о том, что существующие алгоритмы автоматической суммаризации не всегда справляются с задачей краткого пересказа художественного текста. Расхождения во влиянии разных параметров на результат суммаризации указывают на то, что они влияют на результат не так сильно, как обучающая выборка каждой конкретной модели. В перспективе исследования разработка нового инструмента суммаризации путем тонкой настройки моделей с использованием улучшенных версий эталонных кратких содержаний в качестве обучающей выборки.

В данном разделе были описаны результаты экспериментов с большими мультимодальными моделями (VLMs), а также большими языковыми моделями (LLMs), в которых проверялись возможности моделей  в решении задач, связанных с интерпретативной эвристической деятельностью: описание картин из коллекции Государственного Эрмитажа, суммаризация содержания художественных текстов. Так, было установлено, что модели дают более согласованные описания картин, чем информанты, а расхождения с человеческими текстами увеличиваются при усложнении сцены или переходе к абстрактным картинам. Модели пока показывают недостаточное качество суммаризации художественных рассказов, хотя при этом фактов влияния композиционно-эстетической сложности текстов на метрики качества не установлено. 

Кроме того, проведены эксперименты по оценке качества существующих систем автоматического распознавания речи. В качестве материала для такой оценки использовались данные атипичной речи (корпус речи пациентов с афазией) и устной речи в зашумленных условиях, собранные сотрудниками подразделения и представляющие ценность для дальнейших исследований в качестве источника данных. Сформированы бенчмарки для оценки отечественных движков для автоматического распознавания нетипичной речи и для оценки качества диаризации устной спонтанной речи. На основе анализа пяти ведущих отечественных ASR-движков охарактеризован существующий уровень инклюзивности российского сегмента рынка продуктов для ASR.

Представлен эффективный пайплайн для сентимент-анализа отзывов на культурные институции. С помощью многоступенчатого промптинга одна из отечественных больших языковых моделей была дообучена для задачи аспектного сентимент-анализа неструктурированных данных на русском языке. Значения метрик оценки качества сентимент-анализа опередили соответствующие метрики словарного метода и метода анализа с помощью нейронный сетей.  

Наконец, в данном разделе описан один из вариантов исследовательской логики при изучении корпуса текстов русскоязычных социальных сетей. На примере текстов зоообъявлений и гороскопов продемонстрировано, что дискурс социальных сетей, с одной стороны, формирует паттерны нормативной картины мира, а с другой, сам по себе имеет манипулятивный характер.

В данном разделе были описаны структура и содержание трех разработок: системы векторного поиска картин по Цифровой коллекции Государственного Эрмитажа, разработанной в сотрудничестве с компанией “Яндекс.Облако”, а также двух лингвистических корпусов: Корпуса русского рассказа ХХ в., а также Корпуса устной речи студентов.