<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; Квантитативные методы в исследованиях малых языков России и нестандартных разновидностей русского языка – ОТЧЕТ О НАУЧНО-ИССЛЕДОВАТЕЛЬСКОЙ РАБОТЕ</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02_chapter.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bcbce66894bfa8e7e94e40e0186b9bb8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-22a2acbb0f7ec22c15d721aa9f56f094.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_chapter.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Квантитативные методы в исследованиях малых языков России и нестандартных разновидностей русского языка</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ОТЧЕТ О НАУЧНО-ИССЛЕДОВАТЕЛЬСКОЙ РАБОТЕ</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">СПИСОК ИСПОЛНИТЕЛЕЙ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_chapter.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Квантитативные методы в исследованиях малых языков России и нестандартных разновидностей русского языка</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_chapter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Логлаба придумайте название</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_chapter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Формлаба придумайте название</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_chapter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Лаборатория по корпусным технологиям придумайте название!</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_chapter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Исследования морфосинтаксиса и семантики глагольных форм в языках Севера и Арктики</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_chapter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Исследование и сравнительный анализ вариативности обозначения причинно-следственных связей в текстах обучающихся и экспертов, языковых особенностей и возможности орфокоррекции учебных текстов</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_chapter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Моделирование конвергентных процессов в языке и речи цифровыми методами</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">СОДЕРЖАНИЕ</h2>
   
  <ul>
  <li><a href="#ареальная-и-генетическая-вариативность-в-распределении-императивного-междометия-на-возьми-в-языках-кавказа" id="toc-ареальная-и-генетическая-вариативность-в-распределении-императивного-междометия-на-возьми-в-языках-кавказа" class="nav-link active" data-scroll-target="#ареальная-и-генетическая-вариативность-в-распределении-императивного-междометия-на-возьми-в-языках-кавказа"><span class="header-section-number">1.1</span> Ареальная и генетическая вариативность в распределении императивного междометия ‘на, возьми!’ в языках Кавказа</a></li>
  <li><a href="#исследование-дискурсивных-явлений-в-адыгских-языках" id="toc-исследование-дискурсивных-явлений-в-адыгских-языках" class="nav-link" data-scroll-target="#исследование-дискурсивных-явлений-в-адыгских-языках"><span class="header-section-number">1.2</span> Исследование дискурсивных явлений в адыгских языках</a>
  <ul class="collapse">
  <li><a href="#референциальное-линейное-расстояние" id="toc-референциальное-линейное-расстояние" class="nav-link" data-scroll-target="#референциальное-линейное-расстояние"><span class="header-section-number">1.2.1</span> Референциальное линейное расстояние</a></li>
  <li><a href="#одушевлённость" id="toc-одушевлённость" class="nav-link" data-scroll-target="#одушевлённость"><span class="header-section-number">1.2.2</span> Одушевлённость</a></li>
  <li><a href="#протагонистичность" id="toc-протагонистичность" class="nav-link" data-scroll-target="#протагонистичность"><span class="header-section-number">1.2.3</span> Протагонистичность</a></li>
  </ul></li>
  <li><a href="#нестандартные-конструкции-с-количественными-числительными-в-речи-билингвов-корпусное-исследование" id="toc-нестандартные-конструкции-с-количественными-числительными-в-речи-билингвов-корпусное-исследование" class="nav-link" data-scroll-target="#нестандартные-конструкции-с-количественными-числительными-в-речи-билингвов-корпусное-исследование"><span class="header-section-number">1.3</span> Нестандартные конструкции с количественными числительными в речи билингвов: корпусное исследование</a>
  <ul class="collapse">
  <li><a href="#корпусные-данные" id="toc-корпусные-данные" class="nav-link" data-scroll-target="#корпусные-данные"><span class="header-section-number">1.3.1</span> Корпусные данные</a></li>
  <li><a href="#конструкции-с-числительными-в-родных-языках-билингвов" id="toc-конструкции-с-числительными-в-родных-языках-билингвов" class="nav-link" data-scroll-target="#конструкции-с-числительными-в-родных-языках-билингвов"><span class="header-section-number">1.3.2</span> Конструкции с числительными в родных языках билингвов</a></li>
  <li><a href="#разметка-корпусных-данных" id="toc-разметка-корпусных-данных" class="nav-link" data-scroll-target="#разметка-корпусных-данных"><span class="header-section-number">1.3.3</span> Разметка корпусных данных</a></li>
  <li><a href="#cтатистический-анализ-и-его-результаты" id="toc-cтатистический-анализ-и-его-результаты" class="nav-link" data-scroll-target="#cтатистический-анализ-и-его-результаты"><span class="header-section-number">1.3.4</span> Cтатистический анализ и его результаты</a></li>
  </ul></li>
  <li><a href="#rcauctile-и-pycauctile-плиточные-карты-для-визуализации-нахско-дагестанских-языков" id="toc-rcauctile-и-pycauctile-плиточные-карты-для-визуализации-нахско-дагестанских-языков" class="nav-link" data-scroll-target="#rcauctile-и-pycauctile-плиточные-карты-для-визуализации-нахско-дагестанских-языков"><span class="header-section-number">1.4</span> <code>RCaucTile</code> и <code>PyCaucTile</code>: плиточные карты для визуализации нахско-дагестанских языков</a>
  <ul class="collapse">
  <li><a href="#введение" id="toc-введение" class="nav-link" data-scroll-target="#введение"><span class="header-section-number">1.4.1</span> Введение</a></li>
  <li><a href="#лингвистическое-картографирование" id="toc-лингвистическое-картографирование" class="nav-link" data-scroll-target="#лингвистическое-картографирование"><span class="header-section-number">1.4.2</span> Лингвистическое картографирование</a></li>
  <li><a href="#результаты" id="toc-результаты" class="nav-link" data-scroll-target="#результаты"><span class="header-section-number">1.4.3</span> Результаты</a></li>
  <li><a href="#заключение" id="toc-заключение" class="nav-link" data-scroll-target="#заключение"><span class="header-section-number">1.4.4</span> Заключение</a></li>
  </ul></li>
  <li><a href="#опущение-предлогов-в-речи-русско-чувашских-билингвов" id="toc-опущение-предлогов-в-речи-русско-чувашских-билингвов" class="nav-link" data-scroll-target="#опущение-предлогов-в-речи-русско-чувашских-билингвов"><span class="header-section-number">1.5</span> Опущение предлогов в речи русско-чувашских билингвов</a>
  <ul class="collapse">
  <li><a href="#введение-1" id="toc-введение-1" class="nav-link" data-scroll-target="#введение-1"><span class="header-section-number">1.5.1</span> Введение</a></li>
  <li><a href="#методы-и-данные" id="toc-методы-и-данные" class="nav-link" data-scroll-target="#методы-и-данные"><span class="header-section-number">1.5.2</span> Методы и данные</a></li>
  <li><a href="#результаты-1" id="toc-результаты-1" class="nav-link" data-scroll-target="#результаты-1"><span class="header-section-number">1.5.3</span> Результаты</a></li>
  <li><a href="#заключение-1" id="toc-заключение-1" class="nav-link" data-scroll-target="#заключение-1"><span class="header-section-number">1.5.4</span> Заключение</a></li>
  </ul></li>
  <li><a href="#список-глосс" id="toc-список-глосс" class="nav-link" data-scroll-target="#список-глосс"><span class="header-section-number">1.6</span> Список глосс</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Квантитативные методы в исследованиях малых языков России и нестандартных разновидностей русского языка</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Научные исследования лаборатории в 2025 году продолжали общий курс на изучение лингвистических явлений в языках России с помощью квантитативных методов. В рамках проекта продолжились многолетние ареально-типологические исследования языков Кавказа, а также корпусные исследования конкретных явлений в языках Кавказа и в русской речи билингвов, владеющих нестандартными разновидностями русского языка.</p>
<p>В <strong>Разделе 1</strong> описывается исследование императивного междометия ‘на, возьми!’ в языках Кавказа. Такие междометия были найдены почти во всех обследованных языках ареала, но их фонологический облик оказался очень разнообразным. Наиболее частотны и широко распространены междометия, начинающиеся с губно-губного носового согласного типа <em>ma</em> (возможно, появившиеся в автохтонных языках Кавказа под влиянием тюркских языков), но в отдельных регионах встречаются другие локальные варианты. На распределение разных типов междометий влияют и генеалогический, и — в большей степени — ареальный фактор. По мотивам исследования написана статья, поданная в журнал <em>Transactions of the Philological Society</em>.</p>
<p><strong>Раздел 2</strong> представляет два компьютерных ресурса, разработанных сотрудниками лаборатории. Это пакеты <code>RCaucTile</code> и <code>PyCaucTile</code> для языков программирования R и Python, позволяющие визуализировать данные ареально-типологических исследований языков Дагестана с помощью плиточной карты. Такая визуализация облегчает восприятие данных в регионах с высокой языковой плотностью и акцентирует внимание на распределении признаков. Этот инновационный инструмент, впервые использующий плиточные карты для отображения языковых данных, доступен всем пользователям R и Python и может быть применён в дальнейших ареальных исследованиях языков Кавказа.</p>
<p><strong>Раздел 3</strong> посвящён масштабному исследованию организации дискурса в адыгейском и кабардино-черкесском языках, проведённому на материале корпусов лаборатории. К примеру, собранные корпусные данные позволили изучить стратегии референциального выбора в этих языках. Исследование показало, что на выбор стратегии сильнее всего влияет одушевлённость участника и интерференция с другими референтами, вызывающая необходимость различать участников. Для оценки влияния отдельных факторов использовались статистические методы, а для оценки веса разных факторов в общей картине — методы машинного обучения.</p>
<p>В <strong>Разделе 4</strong> описывается исследование нестандартных конструкций с числительными в нестандартной русской речи (у жителей России, владеющих русским как вторым языком). Для этого использовались данные семи корпусов билингвальной русской речи, собранных сотрудниками лаборатории в прошлые годы. Нестандартные конструкции (некорректный с точки зрения литературного русского выбор падежа или числа существительного) встречаются во всех корпусах, но с разной частотностью. С помощью квантитативных методов в исследовании оцениваются разные факторы, влияющие на употребление нестандартных конструкций: сочетание падежа и числа существительного, образование респондента, родной язык и другие. Самым важным фактором оказалась частотность коллокации числительного с существительным — частотные коллокации реже употребляются с нестандартными конструкциями.</p>
<p>В <strong>Разделе 5</strong> представлено ещё одно исследование билингвальной русской речи, посвящённое опущению предлогов у носителей чувашского языка. Исследование показало, что чувашско-русские билингвы довольно часто опускают предлог <em>в</em>, в то время как остальные предлоги подвергаются опущению гораздо реже. Оценка влияния различных параметров на вероятность опущения предлогов, проведённая с помощью статистического анализа, показала, что, вопреки исходным предположениям, социолингвистические факторы (возраст и образование) практически не связаны с опущением, в то время как ряд языковых факторов (в частности, падежная форма и фонологический облик следующего за предлогом слова) значимо влияют на вероятность появления этой нестандартной конструкции.</p>
<section id="ареальная-и-генетическая-вариативность-в-распределении-императивного-междометия-на-возьми-в-языках-кавказа" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="ареальная-и-генетическая-вариативность-в-распределении-императивного-междометия-на-возьми-в-языках-кавказа"><span class="header-section-number">1.1</span> Ареальная и генетическая вариативность в распределении императивного междометия ‘на, возьми!’ в языках Кавказа</h2>
<p>В некоторых языках мира, включая многие языки Кавказа, существуют специальные слова, которые используются в повелительных высказываниях, когда говорящий просит адресата взять что-либо из его рук, как в (1; 2). В ситуации непосредственной коммуникации такие высказывания часто сочетаются с жестом говорящего, протягивающего адресату предмет, который он держит в руках. Такие слова, как агульское <em>ma</em> или русское <em>на</em> (используемое в переводе примеров ниже), не являются глагольными формами императива и вообще глагольными формами, а представляют собой самостоятельные лексемы.</p>
<ol class="example" type="1">
<li>Агульский &lt; лезгинские &lt; нахско-дагестанские (корпус текстов)</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; border-bottom: 0;">
<tbody>
  <tr>
   <td style="text-align:left;"> «ma» </td>
   <td style="text-align:left;"> pu-naa, </td>
   <td style="text-align:left;"> «me </td>
   <td style="text-align:left;"> ik' </td>
   <td style="text-align:left;"> we </td>
   <td style="text-align:left;"> čanta.ji» </td>
  </tr>
  <tr>
   <td style="text-align:left;"> <span style="font-variant:small-caps;">take</span>.<span style="font-variant:small-caps;">it</span> </td>
   <td style="text-align:left;"> говорить.<span style="font-variant:small-caps;">pfv</span>-<span style="font-variant:small-caps;">prf</span> </td>
   <td style="text-align:left;"> этот </td>
   <td style="text-align:left;"> <span style="font-variant:small-caps;">in</span>.класть(<span style="font-variant:small-caps;">imp</span>) </td>
   <td style="text-align:left;"> твой </td>
   <td style="text-align:left;"> сумка(<span style="font-variant:small-caps;">in</span>) </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> '{Дала бутылку с ядом и сказала:} ‘На, положи к себе в сумку.’ '</td></tr></tfoot>
</table>

</div>
</div>
<ol start="2" class="example" type="1">
<li></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; border-bottom: 0;">
<tbody>
  <tr>
   <td style="text-align:left;"> «ma </td>
   <td style="text-align:left;"> čʷa-s </td>
   <td style="text-align:left;"> xibu </td>
   <td style="text-align:left;"> guni» </td>
   <td style="text-align:left;"> pu-na... </td>
  </tr>
  <tr>
   <td style="text-align:left;"> <span style="font-variant:small-caps;">take</span>.<span style="font-variant:small-caps;">it</span> </td>
   <td style="text-align:left;"> вы-<span style="font-variant:small-caps;">dat</span> </td>
   <td style="text-align:left;"> три </td>
   <td style="text-align:left;"> хлеб.<span style="font-variant:small-caps;">abs</span> </td>
   <td style="text-align:left;"> говорить.<span style="font-variant:small-caps;">pfv</span>-<span style="font-variant:small-caps;">cvb</span> </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> '‘Нате вам три хлеба, – сказал он.’ {С этим хлебом пейте молоко.}'</td></tr></tfoot>
</table>

</div>
</div>
<p>Специальные лексемы типа агульского <em>ma</em> или русского <em>на</em> мы будем называть императивными междометиями со значением ‘на, возьми!’ (соответственно, в подстрочных глоссах они будут обозначаться ярлыком «TAKE.IT»). Эти слова являются <strong>императивными</strong> по значению, поскольку встречаются в повелениях, адресованных второму лицу. Они относятся именно к классу <strong>междометий</strong>, а не к глаголам или особым повелительным частицам, которые используются в некоторых языках для придания дополнительной прагматической окраски форме повелительного глагола (типа русской частицы <em>-ка</em>).</p>
<p>Императивные междометия ‘на, возьми!’ можно рассматривать как подтип конативных междометий, функцией которых является получение реакции от адресата <span class="citation" data-cites="dingemanse2023">[<a href="13_references.html#ref-dingemanse2023" role="doc-biblioref">1</a>: 479]</span>. Призывы к тишине вроде <em>шш!</em> <em>цыц!</em> или обращения к животным типа <em>брысь!</em> <em>кыш!</em> <em>тпру!</em> также являются примерами этого типа междометий. Согласно распространенному определению, прототипические междометия — это монолексемные лексические единицы, которые обычно составляют высказывание сами по себе. Повелительные междометия ‘на, возьми!’ не полностью соответствуют этому определению, поскольку они часто встречаются в более полных предложениях, включающих также другие составляющие (см. ниже). Кроме того, в некоторых языках междометие ‘на, возьми!’ может иметь формы словоизменения (например, показатель множественного числа адресата), что делает его отчасти похожим на глагол.</p>
<p>Императивные междометия ‘на, возьми!’ никогда не были предметом специального типологического исследования, хотя более широкий класс императивных междометий привлекал внимание в литературе. Так, А. Ю. Айхенвальд упоминает существование «особых императивных лексем, которые стоят отдельно от других классов слов» и «могут сопровождаться особыми жестами или другими паралингвистическими сигналами с функцией повеления» <span class="citation" data-cites="aikhenvald2010">[<a href="13_references.html#ref-aikhenvald2010" role="doc-biblioref">2</a>: 317–325]</span>. Одним из распространённых типов таких лексем являются императивные слова, обращенные к животным и побуждающие их удалиться из определённого места, приблизиться к говорящему, остановиться или начать движение. Аналогично, Гусев <span class="citation" data-cites="gusev2013">[<a href="13_references.html#ref-gusev2013" role="doc-biblioref">3</a>: 99–102]</span> обсуждает «неглагольные императивы», включая междометия, а также подчеркивает, что в морфосинтаксических терминах мы имеем дело с континуумом между императивными формами глаголов и императивными междометиями, причем между этими двумя крайностями находится довольно много промежуточных форм.</p>
<p>Целью нашего иследования было установление того, в каких <strong>языках Кавказа</strong> имеются специальные императивные междометия со значением ‘на, возьми!’, классификация таких междометий по типу фонологической формы, а также установление морфосинтаксических особенностей междометий с данным значением. В кратком изложении результаты исследования легли в основу одной из глав Типологического атласа языков Дагестана <span class="citation" data-cites="dagatlas">[<a href="13_references.html#ref-dagatlas" role="doc-biblioref">4</a>]</span>, расширенная статья по материалам исследования подана в журнал «Transactions of the Philological Society».</p>
<p>Основными <strong>источниками</strong> данных для этого исследования были словари (в основном двуязычные, в большинстве из которых русский язык является либо первым, либо вторым их пары). В некоторых случаях информация была найдена в грамматиках. Учитывая, что в русском языке есть специальное междометие <em>на!</em> ‘вот, возьми!’ (хотя и омонимичное предлогу <em>на</em>), в словарях или указателях проводился поиск выражения <em>на</em>, которое часто встречалось в качестве отдельного лексического входа русской части. В словарях с доступным текстовым слоем поиск шел по единицам <em>на</em>, (с запятой), <em>нате</em> (форма с суффиксом множественного числа адресата) и по глагольным формам императива 2-го лица единственного числа глаголов, а именно <em>возьми</em> (совершенный вид) и <em>бери</em> (несовершенный вид). В словарях или грамматиках, написанных на английском языке, поиск шел по выражениям <em>take it</em> и <em>take this</em>, в источниках на французском языке — по <em>tiens</em> ‘возьми (это)!’. При этом учитывались только специальные слова для выражения ‘на, возьми!’. Если единственным эквивалентом, предоставленным в источнике, была обычная глагольная форма повелительного наклонения глагола ‘брать, взять’ (например, <em>al</em> ‘возьми!’ в азербайджанском), считалось, что данный язык лишен особого императивного междометия ‘на, возьми!’.</p>
<p>Рассмотрим некоторые типичные примеры употребления императивных междометий ‘на, возьми!’, представленные в источниках. Как правило, такие примеры содержат помимо междометия и другой материал. Практически во всех имеющихся примерах междометие стоит в начале предложения.</p>
<p>Одной из распространенных конструкций, в которых встречаются императивные междометия ‘на, возьми!’, является простое повелительное предложение с <strong>прямым дополнением</strong> (3; 4). В эргативных языках нахско-дагестанской семьи дополнение выражено абсолютивным (номинативным) падежом.</p>
<ol start="3" class="example" type="1">
<li>Хиналугский &lt; нахско-дагестанские <span class="citation" data-cites="ganieva2002">[<a href="13_references.html#ref-ganieva2002" role="doc-biblioref">5</a>: 214]</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; border-bottom: 0;">
<tbody>
  <tr>
   <td style="text-align:left;"> ma </td>
   <td style="text-align:left;"> pšä </td>
  </tr>
  <tr>
   <td style="text-align:left;"> <span style="font-variant:small-caps;">take</span>.<span style="font-variant:small-caps;">it</span> </td>
   <td style="text-align:left;"> bread.<span style="font-variant:small-caps;">abs</span> </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> '‘Возьми хлеб (на хлеб)!’'</td></tr></tfoot>
</table>

</div>
</div>
<ol start="4" class="example" type="1">
<li>Гунзибский &lt; цезские &lt; нахско-дагестанские <span class="citation" data-cites="xalilovisakov2005">[<a href="13_references.html#ref-xalilovisakov2005" role="doc-biblioref">6</a>: 146]</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; border-bottom: 0;">
<tbody>
  <tr>
   <td style="text-align:left;"> hũʔũ </td>
   <td style="text-align:left;"> ẽš </td>
  </tr>
  <tr>
   <td style="text-align:left;"> <span style="font-variant:small-caps;">take</span>.<span style="font-variant:small-caps;">it</span> </td>
   <td style="text-align:left;"> apple.<span style="font-variant:small-caps;">abs</span> </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> '‘Возьми яблоко (на яблоко)!’'</td></tr></tfoot>
</table>

</div>
</div>
<p>Помимо прямого дополнения предложения с повелительными междометиями могут включать <strong>реципиентный</strong> аргумент (обычно в дательном падеже), который в подавляющем большинстве случаев указывает непосредственно на адресата (5).</p>
<ol start="5" class="example" type="1">
<li>Даргинский литературный &lt; даргинские &lt; нахско-дагестанские <span class="citation" data-cites="jusupov2014">[<a href="13_references.html#ref-jusupov2014" role="doc-biblioref">7</a>: 662]</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; border-bottom: 0;">
<tbody>
  <tr>
   <td style="text-align:left;"> ma </td>
   <td style="text-align:left;"> ħed </td>
   <td style="text-align:left;"> žuz </td>
  </tr>
  <tr>
   <td style="text-align:left;"> <span style="font-variant:small-caps;">take</span>.<span style="font-variant:small-caps;">it</span> </td>
   <td style="text-align:left;"> you.<span style="font-variant:small-caps;">sg</span>.<span style="font-variant:small-caps;">dat</span> </td>
   <td style="text-align:left;"> book.<span style="font-variant:small-caps;">abs</span> </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> '‘Возьми книгу (на тебе книгу)!’'</td></tr></tfoot>
</table>

</div>
</div>
<p>Кроме того, нередки примеры, в которых за ‘на, возьми!’ следует повелительная форма обычного глагола, чаще всего собственно ‘брать, взять’, но также и других (6). Предложение, следующее за междометием, может быть и полным повелительным предложением с выраженными аргументами (7). В таких примерах междометие ‘на, возьми!’ может быть отделено запятой от следующей клаузы предложения, хотя это так не во всех примерах.</p>
<ol start="6" class="example" type="1">
<li>Кумыкский &lt; тюркские <span class="citation" data-cites="bammatovgadzhiaxmedov2013">[<a href="13_references.html#ref-bammatovgadzhiaxmedov2013" role="doc-biblioref">8</a>: 20]</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; border-bottom: 0;">
<tbody>
  <tr>
   <td style="text-align:left;"> ma, </td>
   <td style="text-align:left;"> aša! </td>
  </tr>
  <tr>
   <td style="text-align:left;"> <span style="font-variant:small-caps;">take</span>.<span style="font-variant:small-caps;">it</span> </td>
   <td style="text-align:left;"> eat.<span style="font-variant:small-caps;">imp</span> </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> '‘На, ешь!’'</td></tr></tfoot>
</table>

</div>
</div>
<ol start="7" class="example" type="1">
<li>Лезгинский &lt; лезгинские &lt; нахско-дагестанские <span class="citation" data-cites="talibovgadzhiev1966">[<a href="13_references.html#ref-talibovgadzhiev1966" role="doc-biblioref">9</a>: 226]</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; border-bottom: 0;">
<tbody>
  <tr>
   <td style="text-align:left;"> gʷa, </td>
   <td style="text-align:left;"> qːaču </td>
   <td style="text-align:left;"> i </td>
   <td style="text-align:left;"> ktab! </td>
  </tr>
  <tr>
   <td style="text-align:left;"> <span style="font-variant:small-caps;">take</span>.<span style="font-variant:small-caps;">it</span> </td>
   <td style="text-align:left;"> take.<span style="font-variant:small-caps;">imp</span> </td>
   <td style="text-align:left;"> this </td>
   <td style="text-align:left;"> book.<span style="font-variant:small-caps;">abs</span> </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> '‘На, возьми эту книгу!’'</td></tr></tfoot>
</table>

</div>
</div>
<p>Интересной особенностью императивных междометий ‘на, возьми!’ является возможность присоединения суффиксальных показателей <strong>множественного числа адресата</strong> (см. о них <span class="citation" data-cites="zerzele2024">[<a href="13_references.html#ref-zerzele2024" role="doc-biblioref">10</a>]</span>) в тех языках, где такие показатели есть (8). Это свойство императивных междометий свойственно и русскому <em>на!</em> (2 л. ед.ч.) ~ <em>на-те!</em> (2 л. мн.ч.), см. обсуждение в работе <span class="citation" data-cites="gusev2013">[<a href="13_references.html#ref-gusev2013" role="doc-biblioref">3</a>: 99–102]</span>.</p>
<ol start="8" class="example" type="1">
<li>Мегебский &lt; даргинские &lt; нахско-дагестанские <span class="citation" data-cites="dobrushina2019">[<a href="13_references.html#ref-dobrushina2019" role="doc-biblioref">11</a>: 129]</span></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; border-bottom: 0;">
<tbody>
  <tr>
   <td style="text-align:left;"> ma! </td>
   <td style="text-align:left;"> ma-na! </td>
  </tr>
  <tr>
   <td style="text-align:left;"> <span style="font-variant:small-caps;">take</span>.<span style="font-variant:small-caps;">it</span> </td>
   <td style="text-align:left;"> take.it-<span style="font-variant:small-caps;">imp</span>.<span style="font-variant:small-caps;">pl</span> </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> '‘На, возьми!’  ‘Нате, возьмите (к нескольким людям)!’'</td></tr></tfoot>
</table>

</div>
</div>
<p>Обратимся теперь к результатам по варьированию <strong>фонологической формы</strong> императивных междометий ‘на, возьми!’ в языках Кавказа. Прежде всего отметим, что в большинстве языков нашей выборки специальное императивное междометие ‘на, возьми!’ было выявлено. В удинском, азербайджанском и татском языках такого специального элемента нет. В грузинском и армянском языках близкий функциональный эквивалент ‘на, возьми!’, имеющий одну и ту же форму <em>aha</em>, выполняет функцию более общего сигнала внимания (типа ‘вот, обрати внимание!’) и, следовательно, не подпадает под наше понимание специального междометия ‘на, возьми!’. (На карте ниже это междометие, тем не менее, отмечено, чтобы показать своеобразие его ареального распределения.)</p>
<p>В языках, где есть особое императивное междометие ‘на, возьми!’, оно, как правило, имеет односложную форму CV (в некоторых языках также с конечным ларингальным /h/, дающим вариант CVh). В меньшинстве языков, а именно в цезских и нахских группах, ‘на, возьми!’ — двусложное слово со структурой CVCV.</p>
<p>Сегментный состав императивных междометий весьма ограничен. Так, начальными согласными могут быть /m/, /g, gʷ/ или /h/. Гласный после /m/ — /a/ или /ä/. Гласный после /g/ — /o/, а после /gʷ/ — /a/. Таким образом, эти два варианта, скорее всего, связаны звуковым переходом от /gʷa/ к /go/. Наконец, гласный после /h/ может быть как простым, так и назализованным, а именно /a, ã/, /oː/, /ĩː/ и /ũ/.</p>
<p>На карте ниже все междометия типа ‘на, возьми!’ сгруппированы в три основных типа в соответствии с их фонологической формой (<a href="#tbl-1.1" class="quarto-xref">таблица&nbsp;<span>1.1</span></a>). Учитывая, что все междометия CVCV в цезском и нахском языках имеют начальный /h/ и носовой гласный, их можно отнести к типу <em>HA(n)</em>. Грузинское и армянское междометие <em>aha</em> показано на карте как представляющее отдельный тип <em>AHA</em>.</p>
<div id="tbl-1.1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1.1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;1.1 – Формальные типы повелительных междометий «на, возьми!»
</figcaption>
<div aria-describedby="tbl-1.1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 82%">
</colgroup>
<thead>
<tr class="header">
<th>Тип</th>
<th>Примеры</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>MA-type</strong></td>
<td>ma, mah, mä, mäh</td>
</tr>
<tr class="even">
<td><strong>GwA-type</strong></td>
<td>go, gʷa</td>
</tr>
<tr class="odd">
<td><strong>HA(n)-type</strong></td>
<td>ha, hoː, hĩː, hũ, hã; hãʔã, hũʔũ, hãħ(iː) / haħ(iː), hane</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Распределение фонологических типов императивных междометий ‘на, возьми!’ демонстрирует как <strong>генеалогический</strong>, так и <strong>ареальный</strong> сигнал.</p>
<p>Генеалогически обусловленное распределение проявляется в наличии одного и того же типа фонологической формы междометия в пределах одной семьи или одной ветви. Так, тип <em>GwA</em> встречается только в андийских языках (во всех языках этой ветви), а тип <em>HA(n)</em> – только в цезских и нахских (опять же, во всех языках этих ветвей). В свою очередь, тип <em>MA</em> встречается во всех даргинских языках нашей выборки, преобладает в лезгинской ветви (за исключением удинского), а также среди тюркских языков выборки (за исключением азербайджанского). Таким образом, формальный тип побудительных междометий устойчив в отдельных нахско-дагестанских ветвях и, в меньшей степени, среди тюркских языков Дагестана (в двух из трёх языков).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_01_01.jpg" class="img-fluid figure-img" width="928">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.1 – Ареальное распределение фонологических типов междометий ‘на, возьми!’ в языках Кавказа (автор карты – А. А. Иванова)
</figcaption>
</figure>
</div>
</div>
</div>
<p>С другой стороны, в более широкой перспективе можно увидеть чёткий ареальный сигнал в распределении типов. Прежде всего, тип <em>MA</em> преобладает на обширной территории и встречается в центральных и южных ветвях нахско-дагестанских языков (лакской, даргинской, лезгинской, хиналугской), в аварском, который в этом отношении соответствует центральным ветвям, а не андийским или цезским языкам, и в двух тюркских языках (кумыкском и ногайском). Интересно, что ареал <em>MA</em> может охватывать и гораздо большую территорию, поскольку побудительные междометия ‘на, возьми!’ с формой <em>ma</em> также зафиксированы, по крайней мере, в некоторых западнокавказских языках и в карачаево-балкарском (тюркском).</p>
<p>Во-вторых, единственные две ветви с императивными междометиями типа <em>HA(n)</em>, а именно цезские и нахские, географически близки (хотя их разделяет андийская ветвь, имеющая свой собственный уникальный тип <em>GwA</em>).</p>
<p>Наконец, отсутствие императивного междометия ‘на, возьми!’ наблюдается на южной/юго-восточной периферии ареала, а именно в азербайджанском, удинском и татском языках. Эти три языка относятся к трём разным языковым семьям, но распространены на одной территории.</p>
<p>Кроме того, можно отметить, что междометия с формой <em>aha</em> встречаются в двух генеалогически неродственных, но географически смежных языках – грузинском и армянском (ср. также абхазское <em>aħǝ</em>). Помимо общей формы, эти два междометия объединяет также их функция, которая носит более общий характер привлечения внимания, а не собственно повеление ‘возьми!’.</p>
<p>Учитывая выявленное распределение фонологических типов междометий, можно задаться вопросом о том, может ли распространение междометий типа <em>MA</em> на Кавказе быть обусловлено влиянием тюркских языков, которые контактируют как с западнокавказскими (карачаево-балкарский), так и с нахско-дагестанскими языками (кумыкский, азербайджанский, в некоторой степени также ногайский). В качестве альтернативы, тюркские языки Кавказа могли заимствовать междометия типа <em>MA</em> от собственно кавказских языковых семей. Второй сценарий был бы маловероятен, если бы оказалось, что другие тюркские языки, не распространенные на Кавказе, также обладают императивными междометиями ‘на, возьми!’ типа <em>MA</em>. Мы проверили эту возможность, чтобы уменьшить количество гипотетических сценариев распространения междометия.</p>
<p>Тюркские языки образуют большую языковую семью, включающую десятки языков, распространенных на обширной территории Евразии. Для дополнительной выборки, необходимой для проверки наличия в тюркских языках, распространенных за пределами Кавказа, междометия ‘на, возьми!’ типа <em>MA</em>, мы выбрали еще шесть языков в дополнение к четырем названным выше: это туркменский, татарский, узбекский, якутский, хакасский и чувашский, представляющие различные ветви семьи. Как и в случае с нашей основной выборкой, основным источником для этого дополнительного микроисследования были словари. Результаты исследования были однозначными: все шесть тюркских языков дополнительной выборки обладают специальными междометиями ‘на, возьми!’ типа <em>MA</em>: ср. <em>ma</em> в узбекском и хакасском языках, <em>mä</em> в татарском и якутском, <em>me</em> в туркменском и чувашском. Это однозначно свидетельствует о том, что существование междометий типа <em>MA</em> в тюркских языках Кавказа никоим образом не объясняется влиянием автохтонных кавказских языков. Напротив, весьма вероятно, что тюркские языки Кавказа принесли междометия типа <em>MA</em> на Кавказ и могли послужить источником последующего ареального распространения этого типа междометий как в западной (западнокавказские языки), так и в восточной частях Северного Кавказа (нахско-дагестанские языки центральной и южной ветвей). При этом окончательное происхождение междометий типа <em>MA</em> со значением ‘на, возьми!’ в тюркских, а также в монгольских и тунгусских языках остается неясным и требует более широкого межъязыкового исследования.</p>
</section>
<section id="исследование-дискурсивных-явлений-в-адыгских-языках" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="исследование-дискурсивных-явлений-в-адыгских-языках"><span class="header-section-number">1.2</span> Исследование дискурсивных явлений в адыгских языках</h2>
<p>В рамках работы Международной лаборатории языковой конвергенции регулярно собираются и пополняются корпуса абхазо-адыгских языков – как письменные, так и устные. В частности, в 2025 году готовились корпуса преимущественно письменных текстов на абхазском языке (совместно с Академией наук Абхазии) и кабардино-черкесском языке (совместно с кабардинским языковым клубом «Джарез»), а также собирались тексты для устных корпусов адыгейского языка (а. Пшизов, Хачемзий, Егерухай, Хакуринохабль Республики Адыгея; совместно с Адыгейским государственным университетом) и абазинского языка (а. Старо-Кувинск Карачаево-Черкесской республики).</p>
<p>На базе этих корпусов, а также ранее созданных корпусов оказывается возможным проводить сложные исследования, затрагивающие функционирование разнообразных грамматических механизмов в дискурсе и изучать явления, которые невозможно прояснять путем простого опроса консультантов – носителей языка. Существенно, что при этом мы получаем возможность изучить и насколько сильно противопоставлены говоры в отношении рассматриваемых явлений русскому языку и другим идиомам, оказывающим на них влияние.</p>
<p>Примером такого исследования является изучение стратегий референциального выбора в адыгских языках (адыгейском и кабардино-черкесском). В рамках этого исследования было изучено, как долго и какими средствами топики/участники сохраняются в дискурсе, то есть продолжительно упоминаются и остаются в речи. Для этого в устных корпусах, включающих адыгейские тексты из а. Джамбечий и тексты на кубанском диалекте кабардино-черкесского языка из аулов Блечепсин и Ходзь были выделены элементарные дискурсивные единицы (ЭДЕ). С помощью ЭДЕ были измерены референциальная линейная дистанция между данным упоминанием референта и предыдущим, а такжен учтены такие параметры, как одушевленность, интерференция других участников, темпоральная или локальная смена действия, неполная кореферентность участников и протагонистичность. Впрочес, в том, что касалось темпоральной или локальной смены действия, можно было ориентироваться только на явную экспликацию такого изменения, и в результате в выборку попало мало таких случаев (около 18% в Кубанском корпусе и 11% в Джамбечийском), поэтому влияние этого фактора не включалось в анализ.</p>
<p>Примеры из обоих корпусов составили базу данных состоящую из всех анафорических цепочек с контекстом и характеристиками, перечисленными выше, для каждого выражения участника дискурса. Эти базы данных были проанализированы в трех вариантах. В первом варианте присутствуют разные виды референциального выбора: ноль, независимое местоимение, ИГ, редуцированная ИГ, другая ИГ, местоимение + ИГ. Поскольку такое дробное разделение именных групп обычно не используется в литературе, во втором варианте все добавленные категории с ИГ были объединены. Для третьей версии из выборки были удалены все первые упоминания референтов, поскольку такие упоминания не дают новой информации об активации референта в памяти и, кроме того, не обладают всеми приобретенными характеристиками, которые зависят от ближайшего контекста.</p>
<section id="референциальное-линейное-расстояние" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="референциальное-линейное-расстояние"><span class="header-section-number">1.2.1</span> Референциальное линейное расстояние</h3>
<p>Следуя А.Е. Кибрику (<span class="citation" data-cites="kibrik1997">[<a href="13_references.html#ref-kibrik1997" role="doc-biblioref">12</a>]</span>), ниже используются следующие метрики активации для линейного расстояния: при расстоянии 1 указывается показатель ноль, а далее показатель уменьшается на 0.1, пока не доходит до показателя -0.5. В (<a href="07_chapter.html#tbl-1" class="quarto-xref">таблица&nbsp;<span>7.1</span></a>) приведены средние показатели для каждого из референциального выбора в каждом варианте выборки (они зашифрованы следующим образом: Б1 – выборка из Блечепсина, первый вариант; Д1 – выборка из Джамбечий, первый вариант).</p>
<p>Средние значения линейного расстояния для текстов из Блечепсина больше, чем для текстов из Джамбечий, в том числе из-за большего размера самих кубанских текстов (чем больше ЭДЕ в тексте, тем больше возможностей для того, чтобы надолго забыть топик, а потом его вспомнить). Самые маленькие значения принимают независимые местоимения. Впрочем, для полисинтетических языков, где участники могут выражаться прономинальными аффиксами, использование независимых местоимений (особенно, в случае с адыгскими языками, где такие местоимения не несут никакую дополнительную к префиксам информацию) ограничено и маргинально.</p>
<div id="tbl-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;1.2 – Средние значения линейного расстояния.
</figcaption>
<div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Б1</th>
<th>Б2</th>
<th>Б3</th>
<th>Д1</th>
<th>Д2</th>
<th>Д3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ноль</td>
<td>1.46</td>
<td>1.46</td>
<td>1.47</td>
<td>1.09</td>
<td>1.09</td>
<td>1.13</td>
</tr>
<tr class="even">
<td>местоимение</td>
<td>1.21</td>
<td>1.22</td>
<td>1.27</td>
<td>1.14</td>
<td>1.14</td>
<td>1.14</td>
</tr>
<tr class="odd">
<td>именная группа</td>
<td>1.93</td>
<td>2.45</td>
<td>3.88</td>
<td>1.7</td>
<td>1.68</td>
<td>2.27</td>
</tr>
<tr class="even">
<td>редуцированная именная группа</td>
<td>3.27</td>
<td>-</td>
<td>-</td>
<td>1.17</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td>другая именная группа</td>
<td>3.8</td>
<td>-</td>
<td>-</td>
<td>1.86</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>местоимение + именная группа</td>
<td>4.33</td>
<td>-</td>
<td>-</td>
<td>1</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Самая заметная разница между средними значениями возникает в третьей версии каждой из таблиц. Такая разница служит доказательством бóльшей репрезентативности именно третьего варианта данных для этой характеристики, поскольку исключение первых упоминаний (которые были помечены 0 в данных) устраняет искажения, связанные с отсутствием антецедента.</p>
<p>На (<a href="#fig-2" class="quarto-xref">рисунок&nbsp;<span>1.2</span></a>) и (<a href="#fig-3" class="quarto-xref">рисунок&nbsp;<span>1.3</span></a>) можно увидеть пороговые значения линейного расстояния, при котором вероятность использования именной группы превышает 50% - после превышения этого порога ЭДЕ произнесенных после ближайшего упоминания участника, говорящий скорее всего выберет именную группы как выражение референта. Как мы видим, и для блечепсинских, и для джамбечийских текстов этот порог не такой высокий: 2.25 ЭДЕ и 0.97 ЭДЕ соответственно.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_02_01.jpg" class="img-fluid figure-img" width="284">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.2 – Пороговое значение линейного расстояния для именных групп в текстах из Блечепсина.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_02_02.jpg" class="img-fluid figure-img" width="284">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.3 – Пороговое значение линейного расстояния для именных групп в текстах из Джамбечий.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Как видно, несмотря на признанное высокое влияние линейного расстояния на референциальный выбор, в условиях короткого устного адыгского дискурса только линейного расстояния недостаточно для того, чтобы предсказать этот выбор, из-за недостаточной количественной разницы между линейным расстоянием у именной группы и нулевой формы.</p>
</section>
<section id="одушевлённость" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="одушевлённость"><span class="header-section-number">1.2.2</span> Одушевлённость</h3>
<p>Данные по влиянию одушевленности приведены в (<a href="07_chapter.html#tbl-2" class="quarto-xref">таблица&nbsp;<span>7.2</span></a>).</p>
<div id="tbl-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;1.3 – Значения хи-квадрата и коэффициент Крамера V для одушевленности и вида.
</figcaption>
<div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Б1</strong></th>
<th><strong>Б2</strong></th>
<th><strong>Б3</strong></th>
<th><strong>Д1</strong></th>
<th><strong>Д2</strong></th>
<th><strong>Д3</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>χ<sup>2</sup></strong></td>
<td>0.0</td>
<td>0.0001</td>
<td>0.0002</td>
<td>0.0097</td>
<td>0.0012</td>
<td>0.0052</td>
</tr>
<tr class="even">
<td><strong>V</strong></td>
<td>0.307</td>
<td>0.253</td>
<td>0.273</td>
<td>0.266</td>
<td>0.250</td>
<td>0.244</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Так как значения теста хи-квадрата в каждом из вариантов &lt; 0.05, связь между видом и одушевленностью везде значимая, но значения коэффициента Крамера V показывает, что эта связь слабая. Следовательно, изолированно одушевленность слабо влияет на референциальный выбор. Самый большой процент неодушевленных референтов находится среди именных групп.</p>
</section>
<section id="протагонистичность" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="протагонистичность"><span class="header-section-number">1.2.3</span> Протагонистичность</h3>
<p>Статус протагониста часто совмещен с одушевленностью участника. Эти характеристики помогают более медленной деактивации референта в рабочей памяти (<span class="citation" data-cites="kibrik1999">[<a href="13_references.html#ref-kibrik1999" role="doc-biblioref">13</a>]</span>), так что такие референты чаще будут выражаться нулем. Соответствующие данные по текстам из Блечепсина и Джамбечий даны в (<a href="07_chapter.html#tbl-3" class="quarto-xref">таблица&nbsp;<span>7.3</span></a>).</p>
<div id="tbl-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;1.4 – Значения хи-квадрата и коэффициент Крамера V для протагониста и вида выражения.
</figcaption>
<div aria-describedby="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Б1</strong></th>
<th><strong>Б2</strong></th>
<th><strong>Б3</strong></th>
<th><strong>Д1</strong></th>
<th><strong>Д2</strong></th>
<th><strong>Д3</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>χ<sup>2</sup></strong></td>
<td>0.0020</td>
<td>0.0003</td>
<td>0.0072</td>
<td>0.2564</td>
<td>0.6116</td>
<td>0.8409</td>
</tr>
<tr class="even">
<td><strong>V</strong></td>
<td>0.255</td>
<td>0.237</td>
<td>0.208</td>
<td>0.175</td>
<td>0.068</td>
<td>0.044</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Для текстов из Блечепсина связь значима, но слабая, то есть статус протагониста действует совместно с другими факторами. Для текстов из Джамбечий связь между статусом протагониста и вида выражения не является значимой.</p>
<p><strong>Интерференция других участников</strong> связана с наличием других топиков в похожей роли в трех ЭДЕ до рассматриваемого упоминания референта. В (<a href="07_chapter.html#tbl-4" class="quarto-xref">таблица&nbsp;<span>7.4</span></a>) показывается, что связь между интерференцией и референциальным выбором есть. Так как значение коэффициент Крамера V находится в промежутке 0.3-0.5, мы можем назвать эту связь умеренной, то есть интерференция сильнее всех предыдущих характеристик влияет на референциальный выбор. Однако эта связь не является сильной, следовательно, интерференция тоже работает скорее в соединении с другими характеристиками.</p>
<div id="tbl-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;1.5 – Значения хи-квадрата и коэффициент Крамера V для интерференции и вида выражения.
</figcaption>
<div aria-describedby="tbl-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th><strong>Б3</strong></th>
<th><strong>Д3</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>χ<sup>2</sup></strong></td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td><strong>V</strong></td>
<td>0.504</td>
<td>0.348</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>На (<a href="#fig-4" class="quarto-xref">рисунок&nbsp;<span>1.4</span></a>) и (<a href="#fig-5" class="quarto-xref">рисунок&nbsp;<span>1.5</span></a>) мы можем увидеть, что действительно при возникновении такой интерференции говорящий скорее будет выбирать именную группу, а не нулевую форму. В корпусе Джамбечий в таком случае иногда могут использоваться и независимые местоимения.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_02_03.jpg" class="img-fluid figure-img" width="198">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.4 – Распределение типов анафор в зависимости от присутствия интерференции других топиков в трех предыдущих ЭДЕ, Блечепсин.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_02_04.jpg" class="img-fluid figure-img" width="201">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.5 – Распределение типов анафор в зависимости от присутствия интерференции других топиков в трех предыдущих ЭДЕ, Джамбечий.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Неполная кореферентность</strong> с антецедентом возникает, когда анафора восходит к какому-то антецеденту, но их референты не полностью совпадают. Считается, что при проблемах с референции, доступность участника в рабочей памяти будет снижаться, поэтому чаще будут выражаться именными группами (<span class="citation" data-cites="givon1983">[<a href="13_references.html#ref-givon1983" role="doc-biblioref">14</a>]</span>). Итоговые данные по этому параметру приведены в (<a href="07_chapter.html#tbl-5" class="quarto-xref">таблица&nbsp;<span>7.5</span></a>).</p>
<div id="tbl-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;1.6 – Значения хи-квадрата и коэффициент Крамера V для неполной кореферентности и вида.
</figcaption>
<div aria-describedby="tbl-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Б1</strong></th>
<th><strong>Б2</strong></th>
<th><strong>Б3</strong></th>
<th><strong>Д1</strong></th>
<th><strong>Д2</strong></th>
<th><strong>Д3</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>χ<sup>2</sup></strong></td>
<td>0.1664</td>
<td>0.0698</td>
<td>0.0119</td>
<td>0.0526</td>
<td>0.0245</td>
<td>0.0202</td>
</tr>
<tr class="even">
<td><strong>V</strong></td>
<td>0.164</td>
<td>0.135</td>
<td>0.197</td>
<td>0.226</td>
<td>0.186</td>
<td>0.210</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>В тех случаях, когда связь оказывается значимой (в Б3, Д2 и Д3), значение коэффициента Крамера V не превышает 0.3, следовательно, признак неполной кореферентности не является определяющим фактором при референциальном выборе.</p>
<p>В дальнейшем вес разных факторов был соотнесен с помощью деревьев решений. В кубанском корпусе решающим фактором референциального выбора является интерференция – говорящий в первую очередь пытается избежать неоднозначности в выражении участников дискурса. Кроме того, в случаях, когда участник-протагонист не испытывает затруднений с кореферентностью, выбор между именной группой и нулевой анафорой зависит от одушевлённости протагониста, которая выступает решающим фактором. Положительные значения активации, связанные с одушевлённостью, приводят к снижению скорости деактивации участника в рабочей памяти; как следствие, одушевлённый участник чаще выражается нулевой формой.</p>
<p>Перспективным направлением могло бы стать сопоставление полученных данных с материалами других полисинтетических языков как внутри абхазо-адыгской семьи, так и в других языках (ср. исследования (<span class="citation" data-cites="kibrik2011">[<a href="13_references.html#ref-kibrik2011" role="doc-biblioref">15</a>]</span>; <span class="citation" data-cites="bickel2003">[<a href="13_references.html#ref-bickel2003" role="doc-biblioref">16</a>]</span>; <span class="citation" data-cites="arkadievpanova2024">[<a href="13_references.html#ref-arkadievpanova2024" role="doc-biblioref">17</a>]</span>) и др.). Кроме того, аналогичные исследования могут быть приведены для письменной речи, на которую намного большее влияние оказывает русский язык.</p>
</section>
</section>
<section id="нестандартные-конструкции-с-количественными-числительными-в-речи-билингвов-корпусное-исследование" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="нестандартные-конструкции-с-количественными-числительными-в-речи-билингвов-корпусное-исследование"><span class="header-section-number">1.3</span> Нестандартные конструкции с количественными числительными в речи билингвов: корпусное исследование</h2>
<p>Конструкции с количественными числительными в русском языке имеют сложный синтаксис. С числительным в именительном падеже сочетается существительное в родительном падеже множественного числа, например, <em>пять столов</em>. Числительные от 2 до 4 сочетаются с существительным в форме, совпадающей с родительным падежом множественного числа, например, <em>три стола</em>; такие числительные и содержащие их составные (<em>двадцать два</em> и т.п.) далее обозначаются как паукальные. Билингвы – носители русского как неродного (второго) языка – могут использовать нестандартные конструкции с числительными (например, <em>два стол</em> или <em>пять столы</em>).</p>
<p>Цель данного исследования – определить факторы, влияющие на выбор билингвами формы существительного в сочетании с числительным. К возможным факторам относятся влияние родного языка, уровень коллокационности (совместной встречаемости числительного и существительного), тип числительного (собирательные vs.&nbsp;паукальные vs.&nbsp;прочие), а также возраст и уровень образования билингвов.</p>
<section id="корпусные-данные" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="корпусные-данные"><span class="header-section-number">1.3.1</span> Корпусные данные</h3>
<p>В выборку вошли данные из семи билингвальных корпусов Международной лаборатории языковой конвергенции. Исследовались следующие билингвальные разновидности русского языка (в алфавитном порядке): башкирский русский <span class="citation" data-cites="corpus2019">[<a href="13_references.html#ref-corpus2019" role="doc-biblioref">18</a>]</span>, бесермянский русский <span class="citation" data-cites="corpus2020a">[<a href="13_references.html#ref-corpus2020a" role="doc-biblioref">19</a>]</span>, дагестанский русский <span class="citation" data-cites="corpus2018b">[<a href="13_references.html#ref-corpus2018b" role="doc-biblioref">20</a>]</span>, карельский русский <span class="citation" data-cites="corpus2022">[<a href="13_references.html#ref-corpus2022" role="doc-biblioref">21</a>]</span>, марийский русский <span class="citation" data-cites="corpus2023">[<a href="13_references.html#ref-corpus2023" role="doc-biblioref">22</a>]</span>, цыганский русский <span class="citation" data-cites="corpus2020b">[<a href="13_references.html#ref-corpus2020b" role="doc-biblioref">23</a>]</span> и чувашский русский <span class="citation" data-cites="corpus2018a">[<a href="13_references.html#ref-corpus2018a" role="doc-biblioref">24</a>]</span>.</p>
<p>Все корпуса включают непубличную спонтанную речь, записанную в лингвистических экспедициях. Записи представляют собой диалоги или (реже) полилоги между носителями русского языка (интервьюерами, которые являются квалифицированными лингвистами) и билингвами, для которых русский является вторым языком (респондентами).</p>
<p>На первом этапе из билингвальных корпусов были автоматически извлечены все контексты с числительными – 7 376 высказываний. Далее были удалены многочисленные контексты с порядковыми числительными, которые не могут быть определены автоматически (например, в форме <em>двадцать пятый</em> числительное <em>двадцать</em> определяется как количественное), контексты, где существительное отсутствует (<em>в восемь поедем</em>) или является неизменяемым (<em>два такси</em>). Не учитывались примеры с числительным <em>один</em>, существительными, обозначающими количество («тысяча», «миллион» и т.п.), а также с числительными в косвенных падежах. Кроме того, были исключены респонденты, о которых нет никакой социолингвистической информации (7 человек) или не указан родной язык (7 человек).</p>
<p>Таким образом для исследования было отобрано 4 196 высказываний из билингвальных корпусов. В общей сложности была проанализирована речь 181 респондента. Количество респондентов в каждом корпусе, а также их распределение по году рождения и полу представлено в (<a href="#fig-6" class="quarto-xref">рисунок&nbsp;<span>1.6</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_03_01.png" class="img-fluid figure-img" width="1920">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.6 – Год рождения и пол респондентов.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ещё один социолингвистический параметр – уровень образования. Доля респондентов с высшим образованием колеблется от 11% в бесермянском корпусе до 55% в марийском. В 37 случаях эта информация не указана.</p>
</section>
<section id="конструкции-с-числительными-в-родных-языках-билингвов" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="конструкции-с-числительными-в-родных-языках-билингвов"><span class="header-section-number">1.3.2</span> Конструкции с числительными в родных языках билингвов</h3>
<p>Родные языки, которыми владеют билингвы, принадлежат к четырём разным языковым семьям: 1) нахско-дагестанская языковая семья (в корпусе дагестанского русского) – аварский, андийский, багвалинский, тукитинский, акушинский, ицаринский, мегебский, муиринский, цудахарский, лакский, арчинский, рутульский, табасаранский, лакский; 2) тюркская языковая семья – кумыкский и азербайджанский из корпуса дагестанского русского, а также башкирский и чувашский, представленные в одноимённых корпусах; 3) уральская языковая семья – бесермянский, карельский, марийский; 4) индоевропейская языковая семья (индоарийская ветвь) – кэлдэрарский цыганский.</p>
<p>Практически во всех рассмотренных языках, кроме карельского и цыганского, в конструкции с числительными существительное не имеет специальных морфологических показателей. Кроме того, насколько можно судить по имеющимся описаниям, ни в одном языке нет отличий между конструкциями с паукальными и непаукальными числительными.</p>
<p>В грамматиках нахско-дагестанских языков обычно отмечается, что форма существительного не маркируется, см. <span class="citation" data-cites="alekseevetal2012">[<a href="13_references.html#ref-alekseevetal2012" role="doc-biblioref">25</a>: 188]</span> об аварском, <span class="citation" data-cites="zakirova2023">[<a href="13_references.html#ref-zakirova2023" role="doc-biblioref">26</a>: 138–139]</span> о зиловском диалекте андийского языка, <span class="citation" data-cites="kibrik2001">[<a href="13_references.html#ref-kibrik2001" role="doc-biblioref">27</a>: 159]</span> о багвалинском, <span class="citation" data-cites="sumbatovamutalov2003">[<a href="13_references.html#ref-sumbatovamutalov2003" role="doc-biblioref">28</a>: 45]</span> об ицаринском, [Казенин 2013: 29] о лакском и <span class="citation" data-cites="babaliyeva2013">[<a href="13_references.html#ref-babaliyeva2013" role="doc-biblioref">29</a>]</span> о табасаранском. В рассмотренных тюркских языках существительное также не маркируется по числу, как отмечено в <span class="citation" data-cites="johanson1998">[<a href="13_references.html#ref-johanson1998" role="doc-biblioref">30</a>: 51]</span> и некоторых других работах. Пример из кумыкского языка: <em>бир китап</em> ‘одна книга’, <em>беш китап</em> ‘пять книг’ <span class="citation" data-cites="abdullaevaetal2014">[<a href="13_references.html#ref-abdullaevaetal2014" role="doc-biblioref">31</a>: 233]</span>. Среди уральских языков то же касается бесермянского и марийского. Пример из марийского: <em>ик пӧрт</em> ‘один дом’, <em>кандаш пӧрт</em> ‘восемь домов’ <span class="citation" data-cites="rieseetal2022">[<a href="13_references.html#ref-rieseetal2022" role="doc-biblioref">32</a>: 104]</span>.</p>
<p>Регулярное маркирование существительного в конструкции с числительным характерно лишь для двух языков – карельского (уральская языковая семья) и кэлдэрарского цыганского.</p>
<p>В карельском языке в конструкции с числительными используются существительные в партитивном падеже как при паукальных, так и при непаукальных числительных: <em>poika</em> ‘мальчик’, <em>kolme poiku-a</em> ‘три мальчика’, <em>kymmenen poiku-a</em> ‘десять мальчиков’ <span class="citation" data-cites="zaikovrugoeva1999">[<a href="13_references.html#ref-zaikovrugoeva1999" role="doc-biblioref">33,&nbsp;P.&nbsp;140</a>]</span></p>
<p>В языке цыган-кэлдэрар, интервью с которыми включены в корпус цыганского русского, числительные сочетаются с существительными во множественном числе, например: <em>jèkh matòr-a</em> ‘одна машина’ – <em>dùj matòr-</em>» ‘две машины’ <span class="citation" data-cites="oslon2018">[<a href="13_references.html#ref-oslon2018" role="doc-biblioref">34</a>: 464]</span>.</p>
<p>Таким образом, в родных языках респондентов конструкции с числительными, как правило, устроены проще, чем в русском языке. Маркирование существительных в некоторых из них возможно как дополнительный вариант в определенных типах контекстов.</p>
</section>
<section id="разметка-корпусных-данных" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="разметка-корпусных-данных"><span class="header-section-number">1.3.3</span> Разметка корпусных данных</h3>
<p>На первом этапе каждое высказывание было размечено как стандартное или нестандартное. Для дальнейшей обработки данных учитывались высказывания только тех респондентов, у которых нестандартная конструкция зафиксирована хотя бы один раз. Итоговая выборка включала 1 748 высказываний. Доля нестандартных конструкций оказалась выше всего в корпусах дагестанского русского, чувашского русского и марийского русского (см. (<a href="#fig-7" class="quarto-xref">рисунок&nbsp;<span>1.7</span></a>)).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_03_02.png" class="img-fluid figure-img" width="1920">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.7 – Доля нестандартных конструкций с числительными в билингвальных корпусах.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Каждый пример был снабжён социолингвистической информацией (пол, год рождения, уровень образования респондента, родной язык и языковая семья, к которой он относится). Лингвистическая разметка материалов включала несколько параметров. Отмечался тип числительного (паукальное, собирательное или иное). Указывалась лемма существительного.</p>
<p>Для нестандартных примеров указывалась использованная форма существительного. Учитывая, что почти во всех родных языках билингвов в конструкции с числительными существительное не маркируется ни по числу, ни по падежу, можно было ожидать в конструкциях на русском существительное именительного падежа единственного числа. Такие примеры имеются: <em>четыре класс</em> – лакско-русский билингв, <em>три доярка</em> – чувашско-русский билингв и др.. Но вместе с тем оказалось, что возможны и другие формы, например, именительный множественного числа (<em>три ягнята</em> – бесермянско-русский билингв, <em>трое сыновья</em> – марийско-русский билингв). При паукальных числительных во всех корпусах, кроме бесермянского, есть также примеры с существительными в родительном падеже множественного числа (<em>тридцать два учителей нас было</em> – башкирско-русский билингв). В дагестанском и башкирском корпусах при паукальных числительных также отмечены существительные в родительном падеже единственного числа (<em>пять дня</em> – табасаранско-русский билингв). Более подробно результаты разметки по данному параметру представлены в (<a href="#fig-8" class="quarto-xref">рисунок&nbsp;<span>1.8</span></a>). На нем нет материалов цыганского корпуса, поскольку в нём имеется лишь четыре нестандартных примера, во всех используется существительное в именительном падеже множественного числа (<em>три девчата</em>). В этом случае можно предполагать интерференцию с родным языком, но число примеров кажется недостаточным, чтобы с уверенностью это утверждать.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-8" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_03_03.png" class="img-fluid figure-img" width="1920">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.8 – Распределение падежно-числовых форм существительного в нестандартных конструкциях с разными типами числительных.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Графики в (<a href="#fig-8" class="quarto-xref">рисунок&nbsp;<span>1.8</span></a>) показывают, что во всех корпусах со всеми типами числительных преобладает использование существительного в именительном падеже. Существительные в родительном падеже встречаются в нестандартных конструкциях заметно реже. Таким образом, интерференция является не единственной причиной появления нестандартных форм в конструкциях с числительными. Такое влияние можно предполагать лишь в половине всех примеров (там, где используется существительное в именительном падеже единственного числа, а также в примерах из цыганского языка).</p>
<p>При разметке данных было замечено, что ряд очень частотных существительных (<em>час</em>, <em>день</em>, <em>килограмм</em> и т.п.) реже, чем другие, используются в нестандартной форме. Чтобы оценить влияние этого фактора был использован дополнительный параметр – <em>коэффициент коллокационности</em> (dice coefficient). Сначала из Национального корпуса русского языка <a href="ruscorpora.ru">НКРЯ</a> была извлечена мера коллокационности для каждого сочетания <em>числительное + существительное</em> в исследуемой выборке. Затем все коэффициенты для одной леммы существительного были усреднены по всем числительным и объединены с основным набором данных для использования их в логистической модели.</p>
</section>
<section id="cтатистический-анализ-и-его-результаты" class="level3" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="cтатистический-анализ-и-его-результаты"><span class="header-section-number">1.3.4</span> Cтатистический анализ и его результаты</h3>
<p>В качестве основного метода использовалась логистическая регрессия со смешанными эффектами. Модели были созданы в программной среде R [R Core Team 2024] с помощью пакета lme4 <span class="citation" data-cites="bates2014">[<a href="13_references.html#ref-bates2014" role="doc-biblioref">35</a>]</span>. Модель включала следующие переменные (основные эффекты): тип числительного, коэффициент коллокационности, пол, год рождения, образование. Случайными эффектами были переменная <em>респондент</em>, вложенная в переменную <em>языковая семья</em>. Результаты статистического моделирования представлены на следующих графиках (<a href="#fig-9" class="quarto-xref">рисунок&nbsp;<span>1.9</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-9" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_03_04.png" class="img-fluid figure-img" width="1920">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.9 – Вероятность нестандартной формы в зависимости от типа числительного, коэффициента коллокационности и уровня образования респондентов.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Каждый график соответствует группе числительных (слева направо): собирательные, паукальные и прочие. По оси <em>х</em> отмечен коэффициент коллокационности (dice coefficient), по оси <em>у</em> – вероятность нестандартных контекстов. Цветом обозначены уровни образования: красным – высшее, синим – среднее или начальное. Как и ожидалось, вероятность нестандартной формы ниже у респондентов с более высоким уровнем образования. Определенную роль играет тип числительного: для собирательных вероятность использования нестандартной формы самая высокая (но следует учесть, что контекстов с ними в выборке было меньше всего, поэтому на графике большие доверительные интервалы). В конструкциях с высоким коэффициентом коллокационности (<em>два часа</em>, <em>пять километров</em>) вероятность нестандартной формы значительно ниже.</p>
<p>Далее был рассчитан обобщённый коэффициент детерминации (generalized R squared, см. <span class="citation" data-cites="nakagawaschielzeth2013">[<a href="13_references.html#ref-nakagawaschielzeth2013" role="doc-biblioref">36</a>]</span>). Он позволяет выстроить иерархию значимости переменных, которая в данном случае выглядит следующим образом:</p>
<p>коллокационность &gt; уровень образования &gt; год рождения &gt; тип числительного &gt; пол</p>
<p>Наиболее значимой переменной оказалась коллокационность (совместная встречаемость единиц). Чем выше степень коллокационности, тем ниже вероятность появления нестандартной формы в речи билингва. Это можно объяснить с точки зрения когнитивного подхода. Высокочастотные выражения с большей вероятностью попадают в инпут билингвов, чаще успешно воспроизводятся и могут храниться в ментальном лексиконе как единые блоки. В случае с менее частотными сочетаниями неносители языка, вероятно, конструируют фразы «на ходу», что увеличивает вероятность появления нестандартных форм.</p>
</section>
</section>
<section id="rcauctile-и-pycauctile-плиточные-карты-для-визуализации-нахско-дагестанских-языков" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="rcauctile-и-pycauctile-плиточные-карты-для-визуализации-нахско-дагестанских-языков"><span class="header-section-number">1.4</span> <code>RCaucTile</code> и <code>PyCaucTile</code>: плиточные карты для визуализации нахско-дагестанских языков</h2>
<section id="введение" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="введение"><span class="header-section-number">1.4.1</span> Введение</h3>
<p>Плиточная карта –– это вид упрощённой картографической визуализации, на которой географические регионы изображаются соразмерными «плитками», чаще всего квадратами или шестиугольниками. Элементы располагаются на условной сетке координат, сохраняющей примерное взаимное расположение объектов. В настоящей работе предлагается адаптация методологии плиточных карт для визуализации языковых данных. Результатом исследования являются два программных пакета на R и Python, позволяющие создавать такие карты для восточнокавказских языков.</p>
</section>
<section id="лингвистическое-картографирование" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="лингвистическое-картографирование"><span class="header-section-number">1.4.2</span> Лингвистическое картографирование</h3>
<p>Лингвистическое картографирование широко используется в диалектологии и типологии, являясь устоявшимся инструментом для визуализации ареального распределения данных. C. R. Luebbering выделяет несколько видов лингвистических карт – точечные, ареальные, экстраполированные и гибридные, в зависимости от того, представлены ли языки отдельными точками, сплошными областями, плавными градиентами на основе нескольких точек или их комбинацией <span class="citation" data-cites="luebbering2013">[<a href="13_references.html#ref-luebbering2013" role="doc-biblioref">37</a>]</span>. В типологических атласах, включая ставший стандартом Всемирный атлас языковых структур WALS <span class="citation" data-cites="wals">[<a href="13_references.html#ref-wals" role="doc-biblioref">38</a>]</span>, наиболее распространены точечные визуализации, в которых каждому языку соответствует одна координата, цветовое кодирование которой отражает значение признака.</p>
<p>В Типологическом атласе языков Дагестана <span class="citation" data-cites="dagatlas">[<a href="13_references.html#ref-dagatlas" role="doc-biblioref">4</a>]</span>, разработанном в Лаборатории, помимо точечных карт (см. (<a href="#fig-10" class="quarto-xref">рисунок&nbsp;<span>1.10</span></a>)) также используются экстраполированные визуализации, где один язык представлен несколькими точками, соответствующими населенным пунктам, в которых он распространен (см. (<a href="#fig-11" class="quarto-xref">рисунок&nbsp;<span>1.11</span></a>)). Оба варианта карт создаются при помощи программного пакета <code>lingtypology</code>, разработанного Г. А. Морозом <span class="citation" data-cites="moroz2017">[<a href="13_references.html#ref-moroz2017" role="doc-biblioref">39</a>]</span>.</p>
<p>Среди ограничений лингвистических карт отмечают условность и невозможность отражения реальной ситуации многоязычия при представлении языков как единичными точками, так и полигонами <span class="citation" data-cites="drude2018">[<a href="13_references.html#ref-drude2018" role="doc-biblioref">40</a>]</span>. В работах R. K. Macaulay и C. R. Luebbering обсуждаются проблемы читаемости визуализаций: при избытке деталей и высокой языковой плотности карты становятся перегруженными, а распределение признака менее очевидным для восприятия <span class="citation" data-cites="macaulay2014 luebbering2013">[<a href="13_references.html#ref-luebbering2013" role="doc-biblioref">37</a>; <a href="13_references.html#ref-macaulay2014" role="doc-biblioref">41</a>]</span>. Эта проблема является наиболее актуальной для регионов с большим языковым разнообразием, к числу которых относится Восточный Кавказ, где на сравнительно компактной территории распространено более 50 языков из нахско-дагестанской, индоевропейской и тюркской языковых семей.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_04_01.jpeg" class="img-fluid figure-img" width="678">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.10 – Типы утренних приветствий (точечная карта) <span class="citation" data-cites="naccaratoverhees2021">[<a href="13_references.html#ref-naccaratoverhees2021" role="doc-biblioref">42</a>]</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-11" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_04_02.jpeg" class="img-fluid figure-img" width="719">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.11 – Типы утренних приветствий (экстраполированная карта) <span class="citation" data-cites="naccaratoverhees2021">[<a href="13_references.html#ref-naccaratoverhees2021" role="doc-biblioref">42</a>]</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="плиточные-карты" class="level5" data-number="1.4.2.0.1">
<h5 data-number="1.4.2.0.1" class="anchored" data-anchor-id="плиточные-карты"><span class="header-section-number">1.4.2.0.1</span> Плиточные карты</h5>
<p>Плиточные карты рассматриваются в литературе в качестве альтернативы традиционным картографическим визуализациям в ситуациях, когда географическая детализация не является необходимой или даже затрудняет восприятие данных. Как отмечается в исследовании W. Meulemans и др., с возрастанием сложности данных карты, на которых сохраняется ландшафт и точное расположение объектов, становятся менее читаемыми из-за неизбежного совпадения элементов, что требует применения схематизации <span class="citation" data-cites="meulemansetal2020">[<a href="13_references.html#ref-meulemansetal2020" role="doc-biblioref">43</a>]</span>. В регионах с высокой плотностью объектов, согласно M. Loecher и K. Ropkins, визуализации легко становятся перегруженными или страдают от наложения элементов, даже при работе с наборами данных умеренного размера <span class="citation" data-cites="loecherropkins2015">[<a href="13_references.html#ref-loecherropkins2015" role="doc-biblioref">44</a>]</span>.</p>
<p>В плиточных картограммах каждый географический регион представляется в виде образующих единую сетку единообразных плиток идентичного или пропорционального некоторому статистическому признаку размера <span class="citation" data-cites="mcneillhale2017">[<a href="13_references.html#ref-mcneillhale2017" role="doc-biblioref">45</a>]</span>. Преимущество такого подхода заключается в том, что все регионы при корректном подборе размера сохраняют свою различимость: крупные регионы не преобладают в восприятии над малыми. Кроме того, строгая структура сетки систематизирует расположение элементов и облегчает сравнение данных между регионами <span class="citation" data-cites="mcneillhale2017">[<a href="13_references.html#ref-mcneillhale2017" role="doc-biblioref">45</a>]</span>, что делает плиточные карты наиболее подходящими для случаев, когда для визуализации важнее распределение признака среди объектов, чем их географическое положение.</p>
<p>Процесс создания плиточной карты предполагает трансформацию координат, при которой акцент смещается с точных расстояний между объектами на сохранение их смежности, взаимного расположения и глобальной позиции в рамках общей формы территории <span class="citation" data-cites="peterson2011">[<a href="13_references.html#ref-peterson2011" role="doc-biblioref">46</a>]</span>. Несмотря на потерю исходной формы и ландшафта, данный тип визуализации сохраняет узнаваемость для зрителя за счет ментальной карты: как объясняется в работе G. McNeill и S. A. Hale, у зрителей в сознании обычно присутствует сложившийся ментальный образ географической зоны, что снижает необходимость в детализации карты и позволяет эффективно использовать схематизированное представление <span class="citation" data-cites="mcneillhale2017">[<a href="13_references.html#ref-mcneillhale2017" role="doc-biblioref">45</a>]</span>.</p>
</section>
<section id="методология" class="level4" data-number="1.4.2.1">
<h4 data-number="1.4.2.1" class="anchored" data-anchor-id="методология"><span class="header-section-number">1.4.2.1</span> Методология</h4>
<p>Насколько нам известно, плиточные карты ранее не применялись для визуализации языковых данных, что требует адаптации традиционных подходов. В частности, представляется нерелевантным автоматическое определение координат на основе существующих алгоритмов построения плиточных карт, таких как recmap <span class="citation" data-cites="panse2018">[<a href="13_references.html#ref-panse2018" role="doc-biblioref">47</a>]</span>, в силу ограничений таких инструментов и специфики лингвистических данных. В отличие от административных зон с четкими границами, разделяющими территорию на непрерывные участки, языковые ареалы выделяются более условно и распределяются неравномерно, образуя плотные скопления и пустые участки.</p>
<p>Условные координаты на сетке были определены для языков вручную на основе информации о расположении населенных пунктов, соответствующих языкам, с использованием базы данных сел Дагестана и отредактированы с учетом особенностей распределения языков в регионе. При разработке соблюдались три основных принципа, сформулированных для плиточных карт в работе Meulemans и др.: сохранение смежности и взаимного расположения объектов, узнаваемость общей конфигурации и компактность размещения <span class="citation" data-cites="meulemansetal2020">[<a href="13_references.html#ref-meulemansetal2020" role="doc-biblioref">43</a>]</span>.</p>
<p>Разработанные пакеты включают 56 языков, распространенных на территории Восточного Кавказа, из классификации, предложенной в Типологическом атласе языков Дагестана <span class="citation" data-cites="dagatlas">[<a href="13_references.html#ref-dagatlas" role="doc-biblioref">4</a>]</span>. Цветовое кодирование на основе генеалогии также заимствовано из Атласа для обеспечения преемственности визуализаций.</p>
</section>
</section>
<section id="результаты" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="результаты"><span class="header-section-number">1.4.3</span> Результаты</h3>
<section id="техническая-реализация" class="level4" data-number="1.4.3.1">
<h4 data-number="1.4.3.1" class="anchored" data-anchor-id="техническая-реализация"><span class="header-section-number">1.4.3.1</span> Техническая реализация</h4>
<p>Отличительной особенностью разработанного инструмента является его доступность на двух языках программирования – R и Python, что расширяет возможности использования в различных исследовательских средах. Пакеты спроектированы единообразно, совпадая по структуре входных и выходных данных, названиям основных функций и логике работы. <code>RCaucTile</code> реализован на основе библиотеки <code>ggplot2</code>, являющейся стандартом визуализации данных в R. <code>PyCaucTile</code> использует <code>plotnine</code> – Python-реализацию <code>ggplot2</code>, позволяя создавать идентичные визуализации при помощи схожего синтаксиса.</p>
</section>
<section id="структура-данных" class="level4" data-number="1.4.3.2">
<h4 data-number="1.4.3.2" class="anchored" data-anchor-id="структура-данных"><span class="header-section-number">1.4.3.2</span> Структура данных</h4>
<p>В основе пакетов лежит встроенный датасет с информацией о 56 языках из Типологического атласа языков Дагестана. Набор данных включает следующие столбцы, многие из которых совпадают с данными из Атласа: - <code>language</code> –– название языка - <code>branch</code> –– ветвь языковой семьи - <code>family</code> –– семья - <code>glottocode</code> –– код языка из ресурса Glottolog - <code>language_color</code> –– цветовой код для отдельного языка - <code>branch_color</code> –– цветовой код для ветви - <code>x</code>, <code>y</code> –– условные координаты на сетке - <code>abbreviation</code> –– сокращенное название - примеры лингвистических признаков из Атласа (morning_greetings, consonant_inventory_size)</p>
<p>Помимо доступной внутри пакетов информации по двум типологическим признакам, поддерживается работа с пользовательскими данными, что является одной из главных возможностей для исследователей. Для визуализации собственных признаков необходимо подготовить таблицу, содержащую столбец с названиями языков и столбец с соответствующими им значениями признака.</p>
</section>
<section id="типы-карт" class="level4" data-number="1.4.3.3">
<h4 data-number="1.4.3.3" class="anchored" data-anchor-id="типы-карт"><span class="header-section-number">1.4.3.3</span> Типы карт</h4>
<p>Плиточные карты, создаваемые при помощи <code>RCaucTile</code> и <code>PyCaucTile</code>, разделяются на два основных типа в зависимости от визуализируемой информации. Цвет прямоугольника («плитки»), обозначающего язык, может отражать генеалогическую принадлежность языка или значение определенного типологического признака. Базовый шаблон карты, вызываемый ключевой функцией пакета без аргументов, включает языки на сетке координат с цветовым кодированием. Как можно заметить на (<a href="#fig-12" class="quarto-xref">рисунок&nbsp;<span>1.12</span></a>), цвета сгруппированы по языковым ветвям: нахские языки представлены коричневым цветом, андийские –– синим, лезгинская ветвь –– зеленым и так далее.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-12" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_04_03.png" class="img-fluid figure-img" width="1152">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.12 – Плиточная карта с цветовым кодированием на основе генеалогии.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Данный шаблон задает распределение языков по умолчанию и служит основой для карт с отображением типологических признаков. В зависимости от характера признака а различаются два типа карт. Пакеты автоматически определяют характер входных данных и применяют соответствующую схему визуализации.</p>
<p>Категориальные карты используют дискретную цветовую схему для качественных признаков, где каждое значение кодируется отдельным цветом. На (<a href="#fig-13" class="quarto-xref">рисунок&nbsp;<span>1.13</span></a>) представлена плиточная карта на основе встроенного признака из исследования C. Naccarato и S. Verhees, классифицирующего языки по стратегиям утренних приветствий <span class="citation" data-cites="naccaratoverhees2021">[<a href="13_references.html#ref-naccaratoverhees2021" role="doc-biblioref">42</a>]</span>. Карта демонстрирует ареальное распределение трех типов: вопросы о пробуждении, приветствия формата <em>доброе утро</em>, а также присутствие обеих стратегий. Языки, для которых данные по визуализируемому признаку отсутствуют, отображаются светло-серым цветом.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-13" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_04_04.png" class="img-fluid figure-img" width="1152">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.13 – Типы утренних приветствий (карта для категориального признака) <span class="citation" data-cites="naccaratoverhees2021">[<a href="13_references.html#ref-naccaratoverhees2021" role="doc-biblioref">42</a>]</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>В картах на основе числовых признаков применяется градиентная шкала для количественных данных, где интенсивность цвета связана с величиной значения.</p>
<p>В (<a href="#fig-14" class="quarto-xref">рисунок&nbsp;<span>1.14</span></a>) отображено распределение количества согласных фонем в инвентаре согласно данным из Типологического атласа языков Дагестана <span class="citation" data-cites="moroz2021">[<a href="13_references.html#ref-moroz2021" role="doc-biblioref">48</a>]</span>. Градиентная визуализация позволяет быстро оценить ареальное распределение и выявляет языки с наиболее развитыми консонантными системами, представленные светлыми оттенками.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-14" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-14-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_04_05.png" class="img-fluid figure-img" width="1152">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-14-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.14 – Размер инвентаря согласных (карта для числового признака) <span class="citation" data-cites="moroz2021">[<a href="13_references.html#ref-moroz2021" role="doc-biblioref">48</a>]</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Пакеты предоставляют возможность настройки визуализаций для адаптации под формат и цели исследования. Значения признаков могут отображаться непосредственно на плитках рядом с названиями языков, как показано на (<a href="#fig-14" class="quarto-xref">рисунок&nbsp;<span>1.14</span></a>), что особенно эффективно для количественных данных и позволяет быстро оценивать и сравнивать значения. Доступно изменение параметров цветовых палитр, заголовков и легенды, а также модификация языкового шаблона с исключением и сменой названий выбранных языков, что является актуальным при работе с другими генеалогическими классификациями.</p>
</section>
</section>
<section id="заключение" class="level3" data-number="1.4.4">
<h3 data-number="1.4.4" class="anchored" data-anchor-id="заключение"><span class="header-section-number">1.4.4</span> Заключение</h3>
<p>Плиточные карты рассматриваются как альтернативный подход к отображению лингвистических признаков, но не являются полноценной заменой традиционным типологическим картам. Такой метод смещает акцент с географической точности на распределение признака среди языков, может применяться для микротипологических исследований со сравнительным анализом. Плиточные карты представляются актуальными для территорий с высокой языковой плотностью, где традиционные карты сталкиваются с проблемой совпадения элементов и перегруженности. Это создает возможность адаптации разработанной методологии для картографирования других регионов с большим языковым разнообразием.</p>
</section>
</section>
<section id="опущение-предлогов-в-речи-русско-чувашских-билингвов" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="опущение-предлогов-в-речи-русско-чувашских-билингвов"><span class="header-section-number">1.5</span> Опущение предлогов в речи русско-чувашских билингвов</h2>
<section id="введение-1" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="введение-1"><span class="header-section-number">1.5.1</span> Введение</h3>
<p>Обусловленные контактом нестандартные грамматические явления в русской речи билингвов из разных регионов России изучались многими исследователями. <span class="citation" data-cites="danieletal2010">[<a href="13_references.html#ref-danieletal2010" role="doc-biblioref">49</a>]</span> предложили краткий обзор нестандартных явлений в дагестанском варианте русского языка, <span class="citation" data-cites="shagal2016">[<a href="13_references.html#ref-shagal2016" role="doc-biblioref">50</a>]</span> фокусируется на грамматических особенностях речи эрзянских билингвов, <span class="citation" data-cites="stoynovashluinskiy2010">[<a href="13_references.html#ref-stoynovashluinskiy2010" role="doc-biblioref">51</a>]</span> исследуют русскую речь энцев. Некоторые исследования посвящены определенной области грамматики (см. в <span class="citation" data-cites="bubrikh1985">[<a href="13_references.html#ref-bubrikh1985" role="doc-biblioref">52</a>]</span> обзор фонетических и морфологических особенностей в русской речи носителей эрзянского и мокшанского языков) или специфическим нестандартным явлениям, например, нестандартному гендерному маркированию (см. в <span class="citation" data-cites="khomchenkovaetal2018">[<a href="13_references.html#ref-khomchenkovaetal2018" role="doc-biblioref">53</a>]</span> о подверженном контактному влиянию русском языке Северной Сибири и Дальнего Востока) или выпадению предлогов (см. <span class="citation" data-cites="panovaphilippova2021">[<a href="13_references.html#ref-panovaphilippova2021" role="doc-biblioref">54</a>]</span> о дагестанском русском языке).</p>
<p>Данное исследование затрагивает русскую речь чувашских билингвов (далее – чувашский русский язык), которая является примером разновидности русского языка, находящегося в контакте с тюркским языком. Существует множество описаний чувашского языка, в том числе <span class="citation" data-cites="ashmarin1903">[<a href="13_references.html#ref-ashmarin1903" role="doc-biblioref">55</a>]</span>, <span class="citation" data-cites="andreev1961">[<a href="13_references.html#ref-andreev1961" role="doc-biblioref">56</a>]</span>, <span class="citation" data-cites="pavlov2017">[<a href="13_references.html#ref-pavlov2017" role="doc-biblioref">57</a>]</span>, <span class="citation" data-cites="savelyev2020">[<a href="13_references.html#ref-savelyev2020" role="doc-biblioref">58</a>]</span>. Особое значение для данного исследования имеет работа <span class="citation" data-cites="rezyukov1959">[<a href="13_references.html#ref-rezyukov1959" role="doc-biblioref">59</a>]</span>, в которой автор перечисляет различные грамматические явления в чувашском языке и пытается сопоставить их с грамматическими явлениями в русском языке; эта стратегия также прослеживается в <span class="citation" data-cites="bubrikh1985">[<a href="13_references.html#ref-bubrikh1985" role="doc-biblioref">52</a>]</span>. Русский язык, на котором говорят в Чувашии, уже был исследован в работе <span class="citation" data-cites="myiznikov2005">[<a href="13_references.html#ref-myiznikov2005" role="doc-biblioref">60</a>]</span>, где были рассмотрены фонетические, морфологические и лексические особенности лекта. Мызников рассматривает эту разновидность русского языка с диалектологической точки зрения и не исследует конкретные явления <span class="citation" data-cites="myiznikov2005">[<a href="13_references.html#ref-myiznikov2005" role="doc-biblioref">60</a>]</span>. Насколько нам известно, это единственная опубликованная работа, описывающая чувашский русский язык; более того, нет информации об исследованиях в области морфосинтаксиса чувашско-русского языка. Эта область особенно интересна, учитывая различия между морфосинтаксисом в славянских и тюркских языках, которые потенциально могут привести к нестандартным явлениям. На основе данных из корпуса русской речи Чувашии <span class="citation" data-cites="corpus2018a">[<a href="13_references.html#ref-corpus2018a" role="doc-biblioref">24</a>]</span> мы пытаемся выяснить, какие факторы влияют на явление опущения предлогов в чувашском русском и связаны ли эти факторы с языковым контактом.</p>
</section>
<section id="методы-и-данные" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="методы-и-данные"><span class="header-section-number">1.5.2</span> Методы и данные</h3>
<p>Феномен опущения предлогов хорошо изучен для различных языков. Это явление часто упоминается в связи с новогреческим, где опущение предлога <em>se</em> ‘в’ встречается в определенных локативных и указательных контекстах <span class="citation" data-cites="gehrkelekakou2013">[<a href="13_references.html#ref-gehrkelekakou2013" role="doc-biblioref">61</a>]</span>. Тем не менее, в контактных вариантах русского языка это явление не ограничивается такими контекстами: там опущение предлогов встречается также во временных и комитативных предложных группах. <span class="citation" data-cites="caponigropearl2008">[<a href="13_references.html#ref-caponigropearl2008" role="doc-biblioref">62</a>]</span> утверждают, что в английском языке предлоги <em>at</em> (локация) и <em>to</em> (направление), в отличие от <em>from</em> (источник), часто опускаются. Обсуждая опущение предлогов в русском языке, на котором говорят в Дагестане, <span class="citation" data-cites="panovaphilippova2021">[<a href="13_references.html#ref-panovaphilippova2021" role="doc-biblioref">54</a>]</span> представляют следующий список типичных объяснений опущения предлогов:</p>
<ol type="1">
<li>Фонотактические ограничения, с которыми сталкиваются носители второго языка (L2);</li>
<li>Морфосинтаксическая интерференция с другими языками;</li>
<li>Отсутствие семантической маркированности;</li>
<li>Исключительная синтаксическая структура.</li>
</ol>
<p>Авторы опровергают возможность того, что пункты 1 и 4 имеют отношение к их данным; тем не менее, мы включили все представленные объяснения в методологию исследования.</p>
<p>Данное исследование основано на данных, извлеченных из корпуса русского языка, на котором говорят в Чувашии <span class="citation" data-cites="corpus2018a">[<a href="13_references.html#ref-corpus2018a" role="doc-biblioref">24</a>]</span>. Он состоит из интервью с 14 респондентами. Интервью проводились в деревне Малое Карачкино, Чувашия. Для респондентов первым языком (L1) является верхний диалект чувашского языка, вторым (L2) – русский язык. В описании корпуса говорится, что овладение L2 респондентами произошло в подростковом или раннем взрослом возрасте <span class="citation" data-cites="corpus2018a">[<a href="13_references.html#ref-corpus2018a" role="doc-biblioref">24</a>]</span>. Объем корпуса оценивается в 36 140 токенов, не считая речи интервьюеров. Корпус позволяет выполнять базовый поиск по токенам, леммам и тегам, а также выполнять поиск по CQL. Каждый результат поискового запроса сопровождается социолингвистической информацией о говорящем: пол, год рождения и уровень образования.</p>
<p>Корпус русской речи Чувашии <span class="citation" data-cites="corpus2018a">[<a href="13_references.html#ref-corpus2018a" role="doc-biblioref">24</a>]</span> транскрибирован в соответствии со стандартным письменным русским языком, поэтому нестандартные явления, в том числе опущение предлогов, не всегда отражаются в транскрипции. Таким образом, все предложные группы были извлечены двумя способами: путем автоматического и ручного (поиск предложных групп с опущенными предлогами в текстах) извлечения всех контекстов с предлогами. Затем соответствующие фрагменты аудиозаписей были прослушаны. Случаи, в которых было невозможно определить, имело ли место опущение предлога или нет (из-за плохого качества звука, фонового шума или других технических проблем), были удалены из выборки. Наконец, был получен набор данных, состоящий из 2529 контекстов. Все контексты в базе данных были дополнительно аннотированы в соответствии с параметрами, представленными на <a href="#fig-15" class="quarto-xref">рисунок&nbsp;<span>1.15</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-15" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-15-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_05_01.png" class="img-fluid figure-img" width="1350">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-15-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.15 – Значения внутри набора данных. Серые сегменты указывают на то, чтоданных нет.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Столбцы “лемма следующей словоформы” и “коэффициент коллокационности” имеют особо важное значение для выявления связи между выпадением предлога и степенью сочетаемости с ним существительного в предложной группе. Идея о том, что нестандартное явление реже встречается в конструкциях, в которых слова часто встречаются вместе (например, в устойчивых би-граммах), была выдвинута <span class="citation" data-cites="naccaratomoroz2025">[<a href="13_references.html#ref-naccaratomoroz2025" role="doc-biblioref">63</a>]</span> при исследовании нестандартных числительных в билингвальных разновидностях русского языка. Авторы утверждают, что очень часто встречающиеся конструкции, скорее всего, будут храниться в виде целых единиц в ментальном лексиконе, поэтому носители L2 русского реже используют нестандартные формы в контексте частых сочетаний числительных и существительных. Чтобы проверить эту гипотезу на нашей выборке, мы использовали данные Национального корпуса русского языка<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, который использует коэффициент dice в качестве меры коллокационности (<span class="citation" data-cites="nakagawaschielzeth2013">[<a href="13_references.html#ref-nakagawaschielzeth2013" role="doc-biblioref">36</a>]</span>). В тех случаях, когда словосочетание не было найдено в НКРЯ, было установлено значение коэффициента коллокационности 0.</p>
</section>
<section id="результаты-1" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="результаты-1"><span class="header-section-number">1.5.3</span> Результаты</h3>
<p>Всего было рассмотрено 2529 предложных групп, из которых в 340 (13,44%) предлог был опущен. Как показано на <a href="#fig-16" class="quarto-xref">рисунок&nbsp;<span>1.16</span></a>, не все предлоги имели тенденцию к выпадению. Только семь предлогов были пропущены хотя бы один раз: <em>в</em>, <em>у</em>, <em>на</em>, <em>с</em>, <em>из</em>, <em>до</em>, <em>через</em>. Последние два предлога были опущены в выборке только по одному разу. Также стоит отметить, что <em>в</em> и произносится, и опускается значительно чаще, чем другие предлоги: 291 (33,64%) из 865 предлогов <em>в</em> были опущены (см. <a href="#fig-17" class="quarto-xref">рисунок&nbsp;<span>1.17</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-16" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-16-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_05_02.png" class="img-fluid figure-img" width="1012">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-16-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.16 – Количество произнесений и пропусков для каждого предлога.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-17" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-17-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_05_03.png" class="img-fluid figure-img" width="1012">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-17-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.17 – Количество произнесений и пропусков для каждого предлога, склонного к выпадению.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Данные о предлогах, которые не выпадают, мы посчитали избыточными, поэтому последующий анализ был проведен на основе набора данных, который включает только те предлоги, которые имеют тенденцию к выпадению; этот набор данных состоит из 2069 предложных групп.</p>
<p>Чтобы выяснить, какие из факторов, приведенных на <a href="#fig-15" class="quarto-xref">рисунок&nbsp;<span>1.15</span></a>, влияют на опущение предлогов, мы мы применим логистическую регрессионную модель со смешанными эффектами. Для построения более оптимальной модели следует уменьшить число категориальных факторов со множеством переменных: начальный звук следующей словоформы, ее падеж, семантика предложной группы.</p>
<p>Выпадение простых неслоговых предлогов как <em>в</em> в билингвальных разновидностях русского языка часто объясняется влиянием фонотактических ограничений L1. Интересно, что в чувашском русском также есть слоговые предлоги, которые имеют тенденцию к выпадению (<em>у</em>, <em>до</em>). Хотя это указывает на меньшую значимость фонотактики, все еще остается вероятность влияния ограничения на выпадение неслоговых предлогов.</p>
<p>Следует посмотреть на распределение начальных звуков в следующих после предлога словоформах. На <a href="#fig-18" class="quarto-xref">рисунок&nbsp;<span>1.18</span></a> иллюстрируется отношение числа примеров с опущением предлога к числу примеров без опущения. Существует два способа анализа <a href="#fig-18" class="quarto-xref">рисунок&nbsp;<span>1.18</span></a>. Рассматривая вертикальные линии (предлоги), можно сделать вывод, что некоторые предлоги (в частности, <em>в</em>) имеют одинаковую вероятность выпадения в контексте практически любой фонемы, представленной в данных. Большинство предлогов имеют определенные фонемные предпочтения: для <em>у</em> это [i], для <em>с</em> это, что неудивительно, [z], для <em>на</em> это [tʃʲ], для <em>из</em> – [s] и [u]. Еще один способ взглянуть на <a href="#fig-18" class="quarto-xref">рисунок&nbsp;<span>1.18</span></a> – по горизонтали: более светлые линии указывают, в контексте каких фонем чаще всего выпадают предлоги. Согласно рисунку, линии с наиболее светлыми фрагментами соответствуют взрывным звукам: [b], [p]/[pʲ], [d]/[dʲ].</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-18" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_05_04.png" class="img-fluid figure-img" width="1350">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.18 – Отношение числа примеров с опущением предлога к числу примеров без опущения для пар предлог-начальный звук следующей словоформы.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Итак, во-первых, важно добавить в логистическую регрессию параметр самого предлога, поскольку некоторые предлоги имеют тенденцию выпадать в контексте любой фонемы; игнорирование этого факта привело бы к менее точным вычислениям. Во-вторых, вместо того, чтобы добавлять в регрессию множество категориальных переменных, я добавлю только бинарную переменную: взрывной звук далее или нет.</p>
<p>Еще один категориальный фактор с большим количеством переменных – это падеж следующей за предлогом словоформы. На <a href="#fig-19" class="quarto-xref">рисунок&nbsp;<span>1.19</span></a> именительный падеж выделяется больше всего среди других: примерно в трети всех примеров, содержащих именительный падеж, также присутствует опущение предлога. Несмотря на то, что в большинстве пропущенных примеров используется локатив, это может быть просто связано с частотностью падежа.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-19" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_05_05.png" class="img-fluid figure-img" width="1350">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.19 – Обзор падежей, следующих за предлогом словоформ.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Наконец, было принято решение преобразовать категориальный фактор семантики в бинарный фактор ‘неопределенная семантика’/‘определенная семантика’. Таким образом проверяется корреляция между отчетливостью семантики контекста и вероятностью пропуска предлога в указанном контексте. Распределение семантики предложных групп показано на <a href="#fig-20" class="quarto-xref">рисунок&nbsp;<span>1.20</span></a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-20" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/conlab_05_06.png" class="img-fluid figure-img" width="1350">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;1.20 – Обзор семантики предложных групп.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="статистическое-моделирование" class="level4" data-number="1.5.3.1">
<h4 data-number="1.5.3.1" class="anchored" data-anchor-id="статистическое-моделирование"><span class="header-section-number">1.5.3.1</span> Статистическое моделирование</h4>
<p>Чтобы оценить значимость выделенных факторов, мы применили логистическую регрессионную модель со смешанными эффектами, используя пакет R (R Core Team 2024) lme4 <span class="citation" data-cites="bates2014">[<a href="13_references.html#ref-bates2014" role="doc-biblioref">35</a>]</span>. Следуя процедуре пошагового выбора переменных в обратном порядке <span class="citation" data-cites="levshina2015">[<a href="13_references.html#ref-levshina2015" role="doc-biblioref">64</a>]</span>, мы пришли к оптимальной модели (см. <a href="07_chapter.html#tbl-6" class="quarto-xref">таблица&nbsp;<span>7.6</span></a>).</p>
<div id="tbl-6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;1.7 – Переменные в логистической регрессии
</figcaption>
<div aria-describedby="tbl-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 30%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Переменная</th>
<th>Тип переменной</th>
<th>Тип эффекта</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>предлог</td>
<td>категориальная</td>
<td>фиксированный</td>
</tr>
<tr class="even">
<td>спикер</td>
<td>категориальная</td>
<td>случайный</td>
</tr>
<tr class="odd">
<td>возраст</td>
<td>непрерывная</td>
<td>фиксированный</td>
</tr>
<tr class="even">
<td>образование (лет)</td>
<td>непрерывная</td>
<td>фиксированный</td>
</tr>
<tr class="odd">
<td>семантика неопределенная</td>
<td>бинарная</td>
<td>случайный</td>
</tr>
<tr class="even">
<td>начальный звук следующей словоформы взрывной</td>
<td>бинарная</td>
<td>случайный</td>
</tr>
<tr class="odd">
<td>падеж следующей словоформы Именительный</td>
<td>бинарная</td>
<td>фиксированный</td>
</tr>
<tr class="even">
<td>следущая словоформа имеет стандартное падежное маркирование</td>
<td>бинарная</td>
<td>фиксированный</td>
</tr>
<tr class="odd">
<td>коэффициент коллокационности</td>
<td>непрерывная</td>
<td>фиксированный</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Факторы, которые оказались значимыми, представлены в <a href="07_chapter.html#tbl-7" class="quarto-xref">таблица&nbsp;<span>7.7</span></a>.</p>
<div id="tbl-7" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;1.8 – Значимые факторы в логистической регрессии
</figcaption>
<div aria-describedby="tbl-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th>Фактор</th>
<th>Уровень значимости</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>предлог <em>в</em></td>
<td>p &lt; 0.05</td>
</tr>
<tr class="even">
<td>образование (лет)</td>
<td>p &lt; 0.1</td>
</tr>
<tr class="odd">
<td>начальный звук следующей словоформы взравной</td>
<td>p &lt; 0.000</td>
</tr>
<tr class="even">
<td>коэффициент коллокационности</td>
<td>p &lt; 0.05</td>
</tr>
<tr class="odd">
<td>следущая словоформа имеет стандартное падежное маркирование</td>
<td>p &lt; 0.000</td>
</tr>
<tr class="even">
<td>падеж следующей словоформы Именительный</td>
<td>p &lt; 0.000</td>
</tr>
<tr class="odd">
<td>семантика неопределенная</td>
<td>p &lt; 0.01</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="выводы" class="level4" data-number="1.5.3.2">
<h4 data-number="1.5.3.2" class="anchored" data-anchor-id="выводы"><span class="header-section-number">1.5.3.2</span> Выводы</h4>
<p>Опущение предлога <em>в</em> в чувашском русском не следует стандартным социолингвистическим тенденциям (например, в описанных данных пожилые/менее образованные носители языка не используют нестандартный вариант чаще, чем другие). Более того, факторы, которые увеличивают или уменьшают вероятность выпадения для большинства предлогов, – например, начальный звук следующей за предлогом словоформы – не влияют на выпадение <em>в</em>. Полученные данные подтверждают гипотезу о том, что фонотактические ограничения и отсутствие семантической маркированности являются причиной выпадения некоторых предлогов в чувашском русском языке. Аналогичные факторы, влияющие на опущение предлогов, были выявлены в работе <span class="citation" data-cites="panovaphilippova2021">[<a href="13_references.html#ref-panovaphilippova2021" role="doc-biblioref">54</a>]</span>.</p>
<p>Интересно, что некоторые единичные примеры, мотивация которых неясна, следуют общим тенденциям чувашской русской морфосинтаксической системы (например, предлоги, которые были опущены только один раз, были опущены в контексте семантики направления или времени). Другими словами, носители чувашского русского языка распространяют тенденции, которые изначально были мотивированы контактом или неполным усвоением L2, на новые контексты. Это может свидетельствовать о динамичности морфосинтаксической системы чувашского русского языка.</p>
</section>
</section>
<section id="заключение-1" class="level3" data-number="1.5.4">
<h3 data-number="1.5.4" class="anchored" data-anchor-id="заключение-1"><span class="header-section-number">1.5.4</span> Заключение</h3>
<p>Работа, проведённая лабораторией в 2025 году, развивает перспективы использования квантитативных методов в теоретической и типологической лингвистике. Корпуса текстов на малых языках России и на нестандартных разновидностях русского, собранные и поддерживаемые сотрудниками лаборатории, нашли применение в корпусных исследованиях отдельных языковых явлений. Объектомизучения стали не только данные внутри отдельных корпусов, но и сравнение данных разных корпусов билингвального русского между собой. Использование этих результатов многолетней работы лаборатории позволило глубже изучить некоторые отличительные черты в речи русских билингвов (опущение предлогов, нестандартные конструкции с числительными). Корпуса текстов на адыгских языках, собранные в рамках экспедиций НИУ ВШЭ, помогли исследовать дискурсивные явления в этих языках и так же сравнить между собой данные разных идиомов. Многолетний проект ареально-типологических исследования языков Кавказа пополнился как непосредственно типологическим исследованием новой темы (императивные междометия), выявившим генеалогические и ареальные закономерности, так и методологическим новшеством в виде компьютерных инструментов <code>RCaucTile</code> и <code>PyCaucTile</code>, которые позволяют более оптимально визуализировать ареально-типологические данные. Все эти исследовательские работы используют точные методы для изучения языковой конвергенции (свойства ареала, речь билингвов) и смежных языковых явлений.</p>
</section>
</section>
<section id="список-глосс" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="список-глосс"><span class="header-section-number">1.6</span> Список глосс</h2>
<div class="cell">
<div class="cell-output-display">
<p><span class="smallcaps">abs</span>&nbsp;—&nbsp;absolutive; <span class="smallcaps">cvb</span>&nbsp;—&nbsp;converb; <span class="smallcaps">dat</span>&nbsp;—&nbsp;dative; <span class="smallcaps">imp</span>&nbsp;—&nbsp;imperative; <span class="smallcaps">in</span>&nbsp;—&nbsp;in a container; <span class="smallcaps">it</span>&nbsp;—&nbsp;itive; <span class="smallcaps">pfv</span>&nbsp;—&nbsp;perfective; <span class="smallcaps">pl</span>&nbsp;—&nbsp;plural; <span class="smallcaps">prf</span>&nbsp;—&nbsp;perfect; <span class="smallcaps">sg</span>&nbsp;—&nbsp;singular; <span class="smallcaps"><span style="background-color:#00d5ff;">take</span></span>&nbsp;—&nbsp;</p>
</div>
</div>


<div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-dingemanse2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Dingemanse&nbsp;M. <a href="https://til.im/ru/slovar">Interjections</a> // The oxford handbook of word classes / ed. by Lier&nbsp;E. van. —&nbsp;Oxford: Oxford University Press, 2023. —&nbsp;P.&nbsp;477–491.</div>
</div>
<div id="ref-aikhenvald2010" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Aikhenvald&nbsp;A. Y. Imperatives and commands. —&nbsp;Oxford: Oxford University Press, 2010.</div>
</div>
<div id="ref-gusev2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Gusev&nbsp;V. Ju. Tipologija imperativa [typology of the imperative]. —&nbsp;Moscow: Jazyki slavjanskoj kulʹtury, 2013.</div>
</div>
<div id="ref-dagatlas" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Daniel&nbsp;K. F.&nbsp;Michael, Verhees&nbsp;S. <a href="https://lingconlab.ru/tald">Typological atlas of the languages of daghestan (TALD), v. 2.0.0.</a> —&nbsp;Moscow: Linguistic Convergence Laboratory, NRU HSE, 2025.</div>
</div>
<div id="ref-ganieva2002" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Ganieva&nbsp;F. A. Xinalugsko-russkij slovarʹ [khinalug-russian dictionary]. —&nbsp;Makhachkala: DNC RAN, 2002.</div>
</div>
<div id="ref-xalilovisakov2005" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Xalilov&nbsp;I.&nbsp;Madžid Š. Ginuxsko-russkij slovarʹ [hinuq-russian dictionary]. —&nbsp;Makhachkala: DNC RAN Institut jazyka, literatury i iskusstva im. G. Cadasy i Institut èvoljucionnoj antropologii im. M. Planka, 2005.</div>
</div>
<div id="ref-jusupov2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Jusupov&nbsp;X. A. Darginsko-russkij slovarʹ (rukopisʹ) [dargwa-russian dictionary (manuscript)]. —&nbsp;Makhachkala: Institut istorii, jazyka i literatury im. G. Cadasy., 2014.</div>
</div>
<div id="ref-bammatovgadzhiaxmedov2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Bammatov&nbsp;G.&nbsp;Burgan G. Kumyksko-russkij slovarʹ [kumyk-russian dictionary]. —&nbsp;Makhachkala: IJaLI, 2013.</div>
</div>
<div id="ref-talibovgadzhiev1966" class="csl-entry" role="listitem">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Talibov&nbsp;G.&nbsp;Bukar B. Lezginsko-russkij slovarʹ [lezgian-russian dictionary]. —&nbsp;Moscow: Sovetskaja Ènciklopedija, 1966.</div>
</div>
<div id="ref-zerzele2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">Zerzele&nbsp;V. Plural marking on imperatives and prohibitives // ed. by Michael Daniel&nbsp;T. M.&nbsp;Konstantin Filatov. —&nbsp;Moscow: Linguistic Convergence Laboratory, 2024.</div>
</div>
<div id="ref-dobrushina2019" class="csl-entry" role="listitem">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">Dobrushina&nbsp;N. Moods of mehweb // The mehweb language. Essays on phonology, morphology and syntax / ed. by Michael Daniel&nbsp;D. G.&nbsp;Nina Dobrushina. —&nbsp;Berlin: Language Science Press, 2019. —&nbsp;P.&nbsp;117–165.</div>
</div>
<div id="ref-kibrik1997" class="csl-entry" role="listitem">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">Кибрик&nbsp;А. А. Моделирование многофакторного процесса: Выбор референциального средства в русском дискурсе // Вестник Московского университета. —&nbsp;1997. —&nbsp;Is.&nbsp;4. —&nbsp;P.&nbsp;94–105.</div>
</div>
<div id="ref-kibrik1999" class="csl-entry" role="listitem">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Kibrik&nbsp;A. A. Cognitive inferences from discourse observations: Reference and working memory / ed. by K. van Hoek&nbsp;A. A. Kibrik, Noordman&nbsp;L. —&nbsp;Amsterdam: Benjamins, 1999. —&nbsp;P.&nbsp;29–52.</div>
</div>
<div id="ref-givon1983" class="csl-entry" role="listitem">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Givón&nbsp;T. <a href="https://doi:10.1075/tsl.2.06giv">Topic continuity in discourse: The functional domain of switch-reference</a> // Switch reference and universal grammar / ed. by Haiman John&nbsp;M. P. —&nbsp;Amsterdam: John Benjamins Publishing Company, 1983. —&nbsp;Vol.&nbsp;2. —&nbsp;P.&nbsp;51–82.</div>
</div>
<div id="ref-kibrik2011" class="csl-entry" role="listitem">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Kibrik&nbsp;A. <a href="https://doi:10.1093/acprof:oso/9780199215805.001.0001">Reference in discourse</a>. —&nbsp;Oxford: Oxford University Press, 2011.</div>
</div>
<div id="ref-bickel2003" class="csl-entry" role="listitem">
<div class="csl-left-margin">16. </div><div class="csl-right-inline">Bickel&nbsp;B. <a href="https://doi:10.1353/lan.2003.0205">Referential density in discourse and syntactic typology</a> // Language. —&nbsp;2003. —&nbsp;Vol.&nbsp;79, no.&nbsp;4. —&nbsp;P.&nbsp;708–736.</div>
</div>
<div id="ref-arkadievpanova2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">17. </div><div class="csl-right-inline">Arkadiev Peter&nbsp;P. A. Independent pronouns in languages with pronominal affixes: Evidence from abaza // Состав науки: Сборник статей к юбилею веры исааковны подлесской / ed. by Коротаев Н. А.&nbsp;С. Н. Р. —&nbsp;Москва: Буки Веди, 2024. —&nbsp;P.&nbsp;30–58.</div>
</div>
<div id="ref-corpus2019" class="csl-entry" role="listitem">
<div class="csl-left-margin">18. </div><div class="csl-right-inline">Сокур Е. О.&nbsp;М. В. А. Корпус русской речи башкортостана. —&nbsp;Москва: Международная лаборатория языковой конвергенции, НИУ ВШЭ, 2019.</div>
</div>
<div id="ref-corpus2020a" class="csl-entry" role="listitem">
<div class="csl-left-margin">19. </div><div class="csl-right-inline">А.&nbsp;А. Т. Корпус русской речи бесермян. —&nbsp;Москва: Международная лаборатория языковой конвергенции, НИУ ВШЭ, 2020.</div>
</div>
<div id="ref-corpus2018b" class="csl-entry" role="listitem">
<div class="csl-left-margin">20. </div><div class="csl-right-inline">Добрушина Н. Р.&nbsp;Р. фон В.&nbsp;Даниэль М. А. Корпус русской речи дагестана. —&nbsp;Москва: Международная лаборатория языковой конвергенции, НИУ ВШЭ, 2018.</div>
</div>
<div id="ref-corpus2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">21. </div><div class="csl-right-inline">Влахов А. В&nbsp;С. А. А. Е. А. А.&nbsp;Лапина М. С. Корпус русской речи карелии. —&nbsp;Москва: Международная лаборатория языковой конвергенции, НИУ ВШЭ, 2022.</div>
</div>
<div id="ref-corpus2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">22. </div><div class="csl-right-inline">А.&nbsp;В. А. Корпус русской речи республики марий эл. —&nbsp;Москва: Международная лаборатория языковой конвергенции, НИУ ВШЭ, 2023.</div>
</div>
<div id="ref-corpus2020b" class="csl-entry" role="listitem">
<div class="csl-left-margin">23. </div><div class="csl-right-inline">Кожанов К. А.&nbsp;Ч. А. В.&nbsp;Хадасевич А. С. Корпус цыганского русского. —&nbsp;Москва: Международная лаборатория языковой конвергенции, НИУ ВШЭ, 2020.</div>
</div>
<div id="ref-corpus2018a" class="csl-entry" role="listitem">
<div class="csl-left-margin">24. </div><div class="csl-right-inline">Байда (Иванова) К. А.&nbsp;Е. (Кожемякина). А. Д.&nbsp;Холодилова М. A. Корпус русской речи чувашии. —&nbsp;Москва: Международная лаборатория языковой конвергенции, НИУ ВШЭ, 2018.</div>
</div>
<div id="ref-alekseevetal2012" class="csl-entry" role="listitem">
<div class="csl-left-margin">25. </div><div class="csl-right-inline">Алексеев М. Е.&nbsp;М. М. А.&nbsp;Атаев Б. М. Современный аварский язык. —&nbsp;Махачкала: ИЯЛИ ДНЦ РАН, Изд-во АЛЕФ, 2012.</div>
</div>
<div id="ref-zakirova2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">26. </div><div class="csl-right-inline">A.&nbsp;Z. Number marking across different word classes in the east caucasian languages: PhD thesis. —&nbsp;Moscow: HSE University, 2023.</div>
</div>
<div id="ref-kibrik2001" class="csl-entry" role="listitem">
<div class="csl-left-margin">27. </div><div class="csl-right-inline">Кибрик&nbsp;А. Е. Багвалинский язык: Грамматика, тексты, словари. —&nbsp;Москва: ИМЛИ РАН Наследие, 2001.</div>
</div>
<div id="ref-sumbatovamutalov2003" class="csl-entry" role="listitem">
<div class="csl-left-margin">28. </div><div class="csl-right-inline">Sumbatova N. R.&nbsp;M. R. O. A grammar of icari dargwa. —&nbsp;Lincom Europa, 2003.</div>
</div>
<div id="ref-babaliyeva2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">29. </div><div class="csl-right-inline">A.&nbsp;B. Études sur la morphosyntaxe du tabasaran littéraire: PhD thesis. —&nbsp;École Pratique des Hautes Études, 2013.</div>
</div>
<div id="ref-johanson1998" class="csl-entry" role="listitem">
<div class="csl-left-margin">30. </div><div class="csl-right-inline">Johanson&nbsp;L. The structure of turkic // The turkic languages / ed. by L. Johanson&nbsp;É. Á. C. —&nbsp;Routledge, 1998. —&nbsp;P.&nbsp;30–66.</div>
</div>
<div id="ref-abdullaevaetal2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">31. </div><div class="csl-right-inline">Абдуллаева А. З.&nbsp;К. К. С.&nbsp;Гаджиахмедов Н. Э. Современный кумыкский язык / под ред. Н. Э. Гаджиахмедов. —&nbsp;Махачкала: ИЯЛИ ДНЦ РАН, 2014.</div>
</div>
<div id="ref-rieseetal2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">32. </div><div class="csl-right-inline">Riese T.&nbsp;Y. T.&nbsp;Bradley J. <a href="https://grammar.mari-language.com">Mari. An essential grammar for international learners</a>. —&nbsp;University of Vienna, 2022.</div>
</div>
<div id="ref-zaikovrugoeva1999" class="csl-entry" role="listitem">
<div class="csl-left-margin">33. </div><div class="csl-right-inline">Зайков П. М.&nbsp;Р. Л. И. Карельско-русский словарь. —&nbsp;Петрозаводск: Периодика, 1999.</div>
</div>
<div id="ref-oslon2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">34. </div><div class="csl-right-inline">В.&nbsp;О. М. Язык котляров-молдован. Грамматика кэлдэрарского диалекта цыганского языка в русскоязычном окружении. —&nbsp;Москва: Издательский Дом ЯСК, 2018.</div>
</div>
<div id="ref-bates2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">35. </div><div class="csl-right-inline">Bates&nbsp;D. <a href="https://arxiv.org/abs/1406.5823">Fitting linear mixed-effects models using lme4</a>. —&nbsp;2014.</div>
</div>
<div id="ref-nakagawaschielzeth2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">36. </div><div class="csl-right-inline">Nakagawa S.&nbsp;S. H. A general and simple method for obtaining R2 from generalized linear mixed-effects models // Methods Ecol Evol. —&nbsp;2013. —&nbsp;Is.&nbsp;4. —&nbsp;P.&nbsp;133–142.</div>
</div>
<div id="ref-luebbering2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">37. </div><div class="csl-right-inline">Luebbering&nbsp;C. R. Displaying the geography of language: The cartography of language maps // The Linguistics Journal. —&nbsp;2013. —&nbsp;Vol.&nbsp;7, no.&nbsp;1. —&nbsp;P.&nbsp;39–67.</div>
</div>
<div id="ref-wals" class="csl-entry" role="listitem">
<div class="csl-left-margin">38. </div><div class="csl-right-inline"><a href="https://doi.org/10.5281/zenodo.13950591">WALS online</a> / ed. by Dryer&nbsp;M.&nbsp;Matthew S. &amp; Haspelmath. —&nbsp;2013.</div>
</div>
<div id="ref-moroz2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">39. </div><div class="csl-right-inline">Moroz&nbsp;G. Lingtypology: Easy mapping for linguistic typology [r package]. —&nbsp;2017.</div>
</div>
<div id="ref-drude2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">40. </div><div class="csl-right-inline">Drude&nbsp;S. Why we need better language maps, and what they could look like. // Endangered languages and the land: Mapping landscapes of multilingualism. —&nbsp;London: FEL &amp; EL Publishing, 2018. —&nbsp;P.&nbsp;33–40.</div>
</div>
<div id="ref-macaulay2014" class="csl-entry" role="listitem">
<div class="csl-left-margin">41. </div><div class="csl-right-inline">Macaulay&nbsp;R. K. Linguistic maps: Visual aid or abstract art? // Studies in linguistic geography. —&nbsp;Routledge, 2014. —&nbsp;P.&nbsp;172–186.</div>
</div>
<div id="ref-naccaratoverhees2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">42. </div><div class="csl-right-inline">Naccarato Chiara&nbsp;S. V. <a href="https://10.5281/zenodo.6807070">Morning greetings</a> // ed. by Michael Daniel&nbsp;T. M.&nbsp;Konstantin Filatov. —&nbsp;Moscow: Linguistic Convergence Laboratory, 2021.</div>
</div>
<div id="ref-meulemansetal2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">43. </div><div class="csl-right-inline">Meulemans&nbsp;S.&nbsp;W. A simple pipeline for coherent grid maps // IEEE Transactions on Visualization and Computer Graphics. —&nbsp;2020. —&nbsp;Vol.&nbsp;27, no.&nbsp;2. —&nbsp;P.&nbsp;1236–1246.</div>
</div>
<div id="ref-loecherropkins2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">44. </div><div class="csl-right-inline">Loecher&nbsp;&amp;. R.&nbsp;M. RgoogleMaps and loa: Unleashing r graphics power on map tiles // Journal of Statistical Software. —&nbsp;2015. —&nbsp;Vol.&nbsp;63. —&nbsp;P.&nbsp;1–18.</div>
</div>
<div id="ref-mcneillhale2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">45. </div><div class="csl-right-inline">McNeill&nbsp;&amp;. H.&nbsp;G. Generating tile maps // Computer graphics forum. —&nbsp;2017. —&nbsp;Vol.&nbsp;36, no.&nbsp;3. —&nbsp;P.&nbsp;435–445.</div>
</div>
<div id="ref-peterson2011" class="csl-entry" role="listitem">
<div class="csl-left-margin">46. </div><div class="csl-right-inline">Peterson&nbsp;M. P. The tile-based mapping transition in cartography // Maps for the future: Children, education and internet. —&nbsp;Berlin, Heidelberg: Springer Berlin Heidelberg, 2011. —&nbsp;P.&nbsp;151–163.</div>
</div>
<div id="ref-panse2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">47. </div><div class="csl-right-inline">Panse&nbsp;C. Rectangular statistical cartograms in r: The recmap package // Journal of Statistical Software. —&nbsp;2018. —&nbsp;Vol.&nbsp;86. —&nbsp;P.&nbsp;1–27.</div>
</div>
<div id="ref-moroz2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">48. </div><div class="csl-right-inline">Moroz&nbsp;G. On phonology of east caucasian languages // ed. by Michael Daniel&nbsp;T. M.&nbsp;Konstantin Filatov. —&nbsp;Moscow: Linguistic Convergence Laboratory, 2021.</div>
</div>
<div id="ref-danieletal2010" class="csl-entry" role="listitem">
<div class="csl-left-margin">49. </div><div class="csl-right-inline">Daniel&nbsp;D.&nbsp;M. Highlanders’ russian: Case study in bilingualism and language interference in central daghestan // Slavica Helsingiensia. —&nbsp;2010. —&nbsp;Vol.&nbsp;40. —&nbsp;P.&nbsp;65–93.</div>
</div>
<div id="ref-shagal2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">50. </div><div class="csl-right-inline">Shagal&nbsp;K. Contact-induced grammatical phenomena in the russian of erzya speakers // Mordvin languages in the field. —&nbsp;Helsinki: University of Helsinki, 2016. —&nbsp;P.&nbsp;363–377.</div>
</div>
<div id="ref-stoynovashluinskiy2010" class="csl-entry" role="listitem">
<div class="csl-left-margin">51. </div><div class="csl-right-inline">Стойнова&nbsp;&amp;. Ш.&nbsp;Н. М. Русская речь лесных энцев: Зарисовки исследователей вымирающего языка // Slavica Helsingiensia. —&nbsp;2010. —&nbsp;С.&nbsp;153–165.</div>
</div>
<div id="ref-bubrikh1985" class="csl-entry" role="listitem">
<div class="csl-left-margin">52. </div><div class="csl-right-inline">Бубрих&nbsp;Д. В. Русский язык в его отличиях от мордовского. // Проблемы мордовско-русского билингвизма. —&nbsp;Мордов. кн. изд-во, 1985. —&nbsp;С.&nbsp;146–165.</div>
</div>
<div id="ref-khomchenkovaetal2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">53. </div><div class="csl-right-inline">Khomchenkova&nbsp;P.&nbsp;I. Gender disagreement in the contactinfluenced russian of northern siberia and russian far east. —&nbsp;2018. —&nbsp;P.&nbsp;14–15.</div>
</div>
<div id="ref-panovaphilippova2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">54. </div><div class="csl-right-inline">Panova&nbsp;&amp;. P.&nbsp;A. <a href="https://doi.org/10.1177/1367006921990442">When a cross-linguistic tendency marries incomplete acquisition: Preposition drop in russian spoken in daghestan</a> // International Journal of Bilingualism. —&nbsp;2021. —&nbsp;Is.&nbsp;3. —&nbsp;P.&nbsp;640–667.</div>
</div>
<div id="ref-ashmarin1903" class="csl-entry" role="listitem">
<div class="csl-left-margin">55. </div><div class="csl-right-inline">Ашмарин&nbsp;Н. И. Опыт исследования чувашского синтаксиса: Часть первая. —&nbsp;Типолитография Клучникова, 1903.</div>
</div>
<div id="ref-andreev1961" class="csl-entry" role="listitem">
<div class="csl-left-margin">56. </div><div class="csl-right-inline">Андреев&nbsp;Н. А. Краткий грамматический очерк чувашского языка. // Чувашско-русский словарь. —&nbsp;Государственное издательство иностранных и национальных словарей, 1961.</div>
</div>
<div id="ref-pavlov2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">57. </div><div class="csl-right-inline">Павлов&nbsp;И. П. Современный чувашский язык (vol. 2). —&nbsp;Чувашский гос. ин-т гуманитарных наук, 2017.</div>
</div>
<div id="ref-savelyev2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">58. </div><div class="csl-right-inline">Savelyev&nbsp;A. <a href="https://doi.org/10.1093/oso/9780198804628.003.0028">Chuvash and the bulgharic languages</a> // The oxford guide to the transeurasian languages. —&nbsp;2020. —&nbsp;P.&nbsp;446–464.</div>
</div>
<div id="ref-rezyukov1959" class="csl-entry" role="listitem">
<div class="csl-left-margin">59. </div><div class="csl-right-inline">Резюков&nbsp;Н. А. Сопоставительная грамматика чувашского и русского языков. —&nbsp;Гос. изд. Чувашской АССР, 1959.</div>
</div>
<div id="ref-myiznikov2005" class="csl-entry" role="listitem">
<div class="csl-left-margin">60. </div><div class="csl-right-inline">Мызников&nbsp;С. А. Русские говоры среднего поволжья. —&nbsp;Наука, 2005.</div>
</div>
<div id="ref-gehrkelekakou2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">61. </div><div class="csl-right-inline">Gehrke&nbsp;&amp;. L.&nbsp;B. <a href="https://www.academia.edu/2092553/How_to_miss_your_preposition_with_Marika_Lekakou_">How to miss your preposition</a> // Studies in Greek Linguistics. —&nbsp;2013. —&nbsp;Vol.&nbsp;33. —&nbsp;P.&nbsp;92–106.</div>
</div>
<div id="ref-caponigropearl2008" class="csl-entry" role="listitem">
<div class="csl-left-margin">62. </div><div class="csl-right-inline">Caponigro&nbsp;&amp;. P.&nbsp;I. <a href="https://chooser.crossref.org/?doi=10.1075%2Fla.120.18cap">Silent prepositions: Evidence from free relatives.</a> // The syntax and semantics of spatial p. —&nbsp;2008. —&nbsp;P.&nbsp;365–385.</div>
</div>
<div id="ref-naccaratomoroz2025" class="csl-entry" role="listitem">
<div class="csl-left-margin">63. </div><div class="csl-right-inline">Naccarato&nbsp;&amp;. M.&nbsp;C. <a href="https://doi.org/10.1177/13670069251323203">Non-standard numeral constructions in L2 russian: A corpusbased study</a> // International Journal of Bilingualism. —&nbsp;2025.</div>
</div>
<div id="ref-levshina2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">64. </div><div class="csl-right-inline">Levshina&nbsp;N. <a href="https://doi.org/10.1075/z.195.website">How to do linguistics with r</a>. —&nbsp;John Benjamins, 2015.</div>
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>https://ruscorpora.ru/.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="СПИСОК ИСПОЛНИТЕЛЕЙ">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">СПИСОК ИСПОЛНИТЕЛЕЙ</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./02_chapter.html" class="pagination-link" aria-label="Логлаба придумайте название">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Логлаба придумайте название</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>